### PR TITLE
Fix vm freeze for invalid leases in user-v2

### LINKED ISSUE #1827: VM not starting if leases.json contains IP of different subnet
### Description

With user-v2, if the leases.json contains ip with different subnet (than configured in network.yml). VM is not starting

### PR DESCRIPTION
**Pull request by balajiv113**
fixes #1827

### CODE REVIEW

File: pkg/networks/usernet/config.go [hunk 1]
```diff
@@ -85,12 +85,8 @@ func Subnet(name string) (net.IP, error) {
...
 // ParseSubnet converts subnet string to net.IP
-func ParseSubnet(subnet string) (net.IP, error) {
-	subnetIP, _, err := net.ParseCIDR(subnet)
-	if err != nil {
-		return nil, err
-	}
-	return subnetIP, nil
+func ParseSubnet(subnet string) (net.IP, *net.IPNet, error) {
+	return net.ParseCIDR(subnet)
 }
```
Comment (AkihiroSuda) [inline pkg/networks/usernet/config.go:90]: Now you can remove ParseSubnet and just use net.ParseCIDR

**Review by AkihiroSuda — APPROVED** [review]
Thanks
