### PR TITLE
Fix libexec dir detection on Homebrew

### LINKED ISSUE #4295: Homebrew: libexec is ignored
The following PR updates the lima formula to install libexec:
- https://github.com/Homebrew/homebrew-core/pull/252989

```console
$ limactl -v
limactl version 2.0.0-rc.1

$ which limactl
/opt/homebrew/bin/limactl

$ ls /opt/homebrew/opt/lima/libexec/lima/
lima-driver-krunkit* limactl-mcp*
```

However, the installed libexec components are not recognized by lima
```console
$ limactl mcp
FATA[0000] unknown command "mcp" for "limactl" 

$ limactl start --vm-type krunkit
? Creating an instance "default" Proceed with the current configuration
FATA[0002] failed to resolve vm for "/Users/suda/.lima/default/lima.yaml": vmType "krunkit" is not a registered driver
```

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Fix #4295

### CODE REVIEW

File: pkg/usrlocalsharelima/usrlocalsharelima.go [hunk 1]
```diff
@@ -175,20 +175,27 @@ func chooseGABinary(candidates []string) (string, error) {
...
 func LibexecLima() (string, error) {
-	prefix, err := Prefix()
-	if err != nil {
-		return "", err
+	var candidates []string
+	selfDirs := SelfDirs()
+	for _, selfDir := range selfDirs {
+		// selfDir:  /usr/local/bin
+		// prefix: /usr/local
+		// candidate: /usr/local/libexec/lima
```
Comment (afbjorklund) [inline pkg/usrlocalsharelima/usrlocalsharelima.go:186]: Consider also adding "lib"

Comment (AkihiroSuda) [reply pkg/usrlocalsharelima/usrlocalsharelima.go:186]: Why?

Comment (AkihiroSuda) [reply pkg/usrlocalsharelima/usrlocalsharelima.go:186]: added

File: pkg/usrlocalsharelima/usrlocalsharelima.go [hunk 2]
```diff
@@ -73,61 +71,21 @@ func SelfDirs() []string {
...
-			// - dir:   /Applications/Lima.app/Contents/MacOS
-			filepath.Join(selfDir, "lima-guestagent."+ostype+"-"+arch),
-			// candidate 1:
-			// - self:  /usr/local/bin/limactl
-			// - agent: /usr/local/share/lima/lima-guestagent.Linux-x86_64
-			// - dir:   /usr/local/share/lima
-			filepath.Join(selfDirDir, "share/lima/lima-guestagent."+ostype+"-"+arch),
-			// TODO: support custom path
-		)
-		if debugutil.Debug {
```
Comment (norio-nomura) [inline pkg/usrlocalsharelima/usrlocalsharelima.go:105]: This change disrupts the debugging workflow in VSCode.

Comment (AkihiroSuda) [reply pkg/usrlocalsharelima/usrlocalsharelima.go:105]: Moved to
- #4298 

Will fix later there

File: pkg/usrlocalsharelima/usrlocalsharelima.go [hunk 3]
```diff
@@ -175,20 +175,31 @@ func chooseGABinary(candidates []string) (string, error) {
...
+		candidate := filepath.Join(prefix, "libexec", "lima")
+		if ents, err := os.ReadDir(candidate); err == nil && len(ents) > 0 {
+			candidates = append(candidates, candidate)
+		}
+		// selfDir: /opt/homebrew/bin
+		// prefix: /opt/homebrew
+		// candidate: /opt/homebrew/lib/lima
+		//
+		// Note that there is no /opt/homebrew/libexec directory,
+		// as Homebrew preserves libexec for private use.
```
Comment (jandubois) [inline pkg/usrlocalsharelima/usrlocalsharelima.go:197]:
```suggestion
		// as Homebrew reserves libexec for private use.
```

Comment (AkihiroSuda) [reply pkg/usrlocalsharelima/usrlocalsharelima.go:197]: Thanks, fixed in #4298
