### PR TITLE
Fix QEMU issue on binding multiple disks in M1

### LINKED ISSUE #1328: VM doesn't start with multiple additional disk
### Description

```
$ cat working.yaml
images:
- location: "https://cloud-images.ubuntu.com/releases/22.10/release-20221201/ubuntu-22.10-server-cloudimg-arm64.img"
  arch: "aarch64"
  digest: "sha256:9575dfe9f925ec251a933b88a38c5582a18e9d19495025ac01cb2e217e5f14ca"

mounts:
- location: "~"
- location: "/tmp/lima"
  writable: true

additionalDisks:
- "data1"



$ limactl start --name working ./working.yaml
```

```
$ cat not-working.yaml
images:
- location: "https://cloud-images.ubuntu.com/releases/22.10/release-20221201/ubuntu-22.10-server-cloudimg-arm64.img"
  arch: "aarch64"
  digest: "sha256:9575dfe9f925ec251a933b88a38c5582a18e9d19495025ac01cb2e217e5f14ca"

mounts:
- location: "~"
- location: "/tmp/lima"
  writable: true

additionalDisks:
- "data2"
- "data3"

$ limactl start --name not-working ./not-working.yaml
? Creating an instance "not-working" Proceed with the current configuration
INFO[0001] Attempting to download the image from "https://cloud-images.ubuntu.com/releases/22.10/release-20221201/ubuntu-22.10-server-cloudimg-arm64.img"  digest="sha256:9575dfe9f925ec251a933b88a38c5582a18e9d19495025ac01cb2e217e5f14ca"
INFO[0001] Using cache "/Users/trahman/Library/Caches/lima/download/by-url-sha256/6bbad93b29a1faf5328aac270b23b85f75b3fce9d579c3e5bc91b7abfb870647/data"
INFO[0001] Attempting to download the nerdctl archive from "https://github.com/containerd/nerdctl/releases/download/v1.1.0/nerdctl-full-1.1.0-linux-arm64.tar.gz"  digest="sha256:3b613a1be5a24460c44bb93a3609b790ada94e06efd1a86467d45bec7da8b449"
INFO[0001] Using cache "/Users/trahman/Library/Caches/lima/download/by-url-sha256/c69be86b3e48430e3d687d54361cf15b90e2c067fae6a294ca6292d41f42bf0e/data"
INFO[0002] [hostagent] Mounting disk "data2" on "/mnt/lima-data2"
INFO[0002] [hostagent] Mounting disk "data3" on "/mnt/lima-data3"
INFO[0002] [hostagent] Starting QEMU (hint: to watch the boot progress, see "/Users/trahman/.lima/not-working/serial.log")
INFO[0002] SSH Local Port: 52063
INFO[0002] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0002] [hostagent] Driver stopped due to error: "exit status 1"
INFO[0002] [hostagent] Shutting down the host agent
WARN[0002] [hostagent] failed to exit SSH master
INFO[0002] [hostagent] Shutting down QEMU with ACPI
WARN[0002] [hostagent] failed to open the QMP socket "/Users/trahman/.lima/not-working/qmp.sock", forcibly killing QEMU
WARN[0002] [hostagent] failed to kill QEMU
INFO[0012] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0022] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0032] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0042] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0052] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0062] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0072] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0083] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0093] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0103] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0113] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0123] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0133] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0143] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0153] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0163] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0173] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0183] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
```

it remains stuck at this phase for some time and exits with `FATA[0617] did not receive an event with the "running" status`

### PR DESCRIPTION
**Pull request by balajiv113**
fixes #1328 

Not sure on why happening only in M1. Changing the -cdrom to -device as mentioned in https://lists.gnu.org/archive/html/qemu-discuss/2014-04/msg00052.html fixes this issue

### CODE REVIEW

File: pkg/qemu/qemu.go [hunk 1]
```diff
@@ -466,7 +466,7 @@ func Cmdline(cfg Config) (string, []string, error) {
 			"-device", "scsi-cd,bus=scsi0.0,drive=cdrom0")
 	default:
 		// TODO: consider using virtio cdrom for all the architectures
```
Comment (AkihiroSuda) [inline pkg/qemu/qemu.go:468]: Can we use this? (See the riscv64 code above)

Comment (BalajiVijayakumar1195) [reply pkg/qemu/qemu.go]: Done the changes.
Verified working in intel and mac m1.

Comment (balajiv113) [reply pkg/qemu/qemu.go]: Done the changes.
Verified in Intel and M1

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Review by jandubois — APPROVED** [review]
Thanks!

Confirmed on macOS Ventura on M1 Ultra.
