### PR TITLE
fix(shell-sync): show both rsync & diff stats for `View the changed contents`

### LINKED ISSUE #4693: `limactl shell --sync`: "View the changed contents" does not show new files
```console
$ limactl shell --sync . default touch new_file
INFO[0000] Syncing host current directory(/Users/suda/test) to guest instance... 
INFO[0000] Successfully synced host current directory to guest(/home/suda.guest/Users/suda/test) instance. 
? ⚠️  Accept the changes? (added: 1, deleted: 0, modified: 0)  [Use arrows to move, type to filter]
  Yes
  No
> View the changed contents
```

"View the changed contents" does not show the `new_file`

### PR DESCRIPTION
**Pull request by unsuman**
Fixes #4693 

Using `diff -ruN` fails to report newly added empty files when comparing directories. A workaround here is to show both the rsync dry-run stats and the diff output:
``` 
> View the changed contents

=== RSYNC DRY-RUN STATISTICS ===
added: 0, deleted: 0, modified: 1

Transfer starting: 10 files
>f..t.... test/new_file

sent 22 bytes  received 286 bytes  3080k bytes/sec
total size is 6191  speedup is 20.10



=== DETAILED DIFF ===
```

### CODE REVIEW

File: cmd/limactl/shell.go [hunk 1]
```diff
@@ -528,6 +528,21 @@ func askUserForRsyncBack(ctx context.Context, cmd *cobra.Command, inst *limatype
...
+
+			// Write rsync dry-run output first
+			if stats != nil {
+				combinedOutput := fmt.Sprintf(
+					"=== RSYNC DRY-RUN STATISTICS ===\n%s\n\n%s\n\n\n=== DETAILED DIFF ===\n\n\n",
+					stats.String(),
+					stats.Output,
+				)
+
+				if _, err := pipeIn.Write([]byte(combinedOutput)); err != nil {
```
Comment (jandubois) [inline cmd/limactl/shell.go]:
```suggestion
				if _, err := fmt.Fprint(pipeIn, combinedOutput); err != nil {
```

File: cmd/limactl/shell.go [hunk 2]
```diff
@@ -622,6 +637,7 @@ type rsyncStats struct {
 	Added    int
 	Deleted  int
 	Modified int
+	Output   string
```
Comment (jandubois) [inline cmd/limactl/shell.go]: I would call it `Raw` instead of `Output`, but it feels odd to mix parsed and raw data in a single structure. I think returning it as a separate value from the function would be cleaner.

File: cmd/limactl/shell.go [hunk 3]
```diff
@@ -656,7 +672,13 @@ func getRsyncStats(ctx context.Context, source, destination string) (*rsyncStats
 	if err != nil {
 		return nil, err
 	}
-	return parseRsyncStats(string(out)), nil
+	if len(out) == 0 {
```
Comment (jandubois) [inline cmd/limactl/shell.go]: Why do you want to suppress the output when there are no changes? I would prefer to see a "no changes" messages to no output.

File: cmd/limactl/shell.go [hunk 4]
```diff
@@ -528,6 +528,21 @@ func askUserForRsyncBack(ctx context.Context, cmd *cobra.Command, inst *limatype
 			if err := lessCmd.Start(); err != nil {
 				return fmt.Errorf("failed to start less: %w", err)
 			}
+
+			// Write rsync dry-run output first
+			if stats != nil {
+				combinedOutput := fmt.Sprintf(
+					"=== RSYNC DRY-RUN STATISTICS ===\n%s\n\n%s\n\n\n=== DETAILED DIFF ===\n\n\n",
```
Comment (jandubois) [inline cmd/limactl/shell.go]: This may be personal preference, but I find this too much yelling. I think more subdued headers would look better, e.g.

```suggestion
					"--- rsync dry-run statistics ---\n%s\n\n%s\n\n\n--- detailed diff ---\n\n\n",
```

**Review by jandubois — DISMISSED** [review]
Sorry, but I really only want to see "No changes", without the whole rsync dry-run and empty diff output.

I thought the command should provide feedback to the user, but I think it should still be special cased to not show

```
--- rsync dry-run statistics ---

No changes

--- detailed diff ---
```

Otherwise the PR is fine, but I would prefer this to still look a little nicer.

**Comment by unsuman** [comment]
I think if there are no changes, it's better not show the interactive prompt at all.

**Comment by unsuman** [comment]
Also made the headers grey 
Screenshot 2026-03-12 at 12 01 57 PM
