### PR TITLE
Make sure macOS version is in dotted-tri format

### LINKED ISSUE #868: hostagent fails to parse macOS version 12.4
### Description

I just noticed this warning with lima 0.11.0 on MacOS 12.4

```
WARN[0000] [hostagent] failed to parse macOS version "12.4": 12.4 is not in dotted-tri format
```

### PR DESCRIPTION
**Pull request by jandubois**
Fixes #868

### CODE REVIEW

File: pkg/qemu/qemu.go [hunk 1]
```diff
@@ -284,6 +284,10 @@ func getMacOSProductVersion() (*semver.Version, error) {
 		return nil, fmt.Errorf("failed to execute %v: %w", cmd.Args, err)
 	}
 	verTrimmed := strings.TrimSpace(string(b))
+	// macOS 12.4 returns just "12.4\n"
+	for strings.Count(verTrimmed, ".") < 2 {
+		verTrimmed += ".0"
```
Comment (AkihiroSuda) [inline pkg/qemu/qemu.go:289]: += ".0.0" when count == 0

Comment (jandubois) [reply pkg/qemu/qemu.go:289]: That's why it is in a `for` loop, so it will loop twice in that case: https://go.dev/play/p/j_0P1mZWRtj

**Review by AkihiroSuda — APPROVED** [review]
Thanks
