### PR TITLE
Fix '"debug build detected" is always printed' issue

### LINKED ISSUE #2684: "debug build detected" is always printed even when `--debug` is not set
```console
$ limactl start
[...]
INFO[0000] [hostagent] debug build detected, adding more guest agent candidates: /usr/_output/share/lima/lima-guestagen
t.Linux-x86_64
[...]
```

Caused by:
- https://github.com/lima-vm/lima/pull/2651

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Fix #2684

### CODE REVIEW

**Review by norio-nomura — APPROVED** [review]
LGTM!

We might want to consider rephrasing this message: `debug build detected, adding more guest agent candidates: ...`

File: pkg/usrlocalsharelima/usrlocalsharelima.go [hunk 1]
```diff
@@ -50,14 +51,14 @@ func Dir() (string, error) {
 		filepath.Join(selfDirDir, "share/lima/lima-guestagent."+ostype+"-"+arch),
 		// TODO: support custom path
 	}
-	if logrus.GetLevel() == logrus.DebugLevel {
+	if debugutil.Debug {
```
Comment (nirs) [inline pkg/usrlocalsharelima/usrlocalsharelima.go:54]: Do we need a new package for keeping one flag?

If we do, I would change the names so we can use:

```go
if debug.Enabled {
    ...
}
```

Comment (AkihiroSuda) [reply pkg/usrlocalsharelima/usrlocalsharelima.go:54]: Yes, as it is referred from several pkgs.

I avoided "debug" because it conflicts with variable names

**Review by nirs — APPROVED** [review]

File: pkg/usrlocalsharelima/usrlocalsharelima.go [hunk 2]
```diff
@@ -50,14 +51,14 @@ func Dir() (string, error) {
...
 		// candidate 2: lauched by `~/go/bin/dlv dap`
 		// - self: ${workspaceFolder}/cmd/limactl/__debug_bin_XXXXXX
 		// - agent: ${workspaceFolder}/_output/share/lima/lima-guestagent.Linux-x86_64
 		// - dir:  ${workspaceFolder}/_output/share/lima
 		candidateForDebugBuild := filepath.Join(filepath.Dir(selfDirDir), "_output/share/lima/lima-guestagent."+ostype+"-"+arch)
 		gaCandidates = append(gaCandidates, candidateForDebugBuild)
-		logrus.Infof("debug build detected, adding more guest agent candidates: %v", candidateForDebugBuild)
+		logrus.Infof("debug mode detected, adding more guest agent candidates: %v", candidateForDebugBuild)
```
Comment (norio-nomura) [inline pkg/usrlocalsharelima/usrlocalsharelima.go:61]: 👍

**Review by norio-nomura — APPROVED** [review]
