### PR TITLE
Fix DNS not propagated from base template

### LINKED ISSUE #4760: DNS settings are not propagated when using a base template
### Description

DNS settings are not propagated from base template to main template.
> Discussion on [Slack](https://cloud-native.slack.com/archives/C043N6ZFV9S/p1773853580695349)

### Base template:
```yaml
# Debian 13 (trixie) base image
images:
  - location: "https://cdimage.debian.org/images/cloud/trixie/20260316-2418/debian-13-generic-amd64-20260316-2418.qcow2"
    arch: "x86_64"
    digest: "sha512:c6523db54404e320ed30787038f155f649995392697fa2a41e49458d36e056fda020593a03cf910fa7bf93bd5c510b12d6e7c7bf7852a03ee3a64536fecf0127"
  - location: "https://cdimage.debian.org/images/cloud/trixie/20260316-2418/debian-13-generic-arm64-20260316-2418.qcow2"
    arch: "aarch64"
    digest: "sha512:f0460932cd6992539c7c9142bb02a24af83243503bad0179b0813bd6269195785655348ea889daf5927f80853f63b3402a78176967854887dbca9da3859599a0"
  # Fallback images
  - location: "https://cloud.debian.org/images/cloud/trixie/latest/debian-13-generic-amd64.qcow2"
    arch: "x86_64"
  - location: "https://cloud.debian.org/images/cloud/trixie/latest/debian-13-generic-arm64.qcow2"
    arch: "aarch64"

mounts: []
# containerd is managed by k3s, not by Lima, so the values are set to false here.
containerd:
  system: false
  user: false
dns:
  - 1.1.1.1
  - 8.8.8.8

hostResolver:
  enabled: false

provision:
  - mode: system
    script: |
      #!/bin/sh
      if [ ! -f /usr/bin/fish ]; then
        apt update
        apt install -y curl gnupg2
        echo 'deb https://download.opensuse.org/repositories/shells:/fish:/release:/4/Debian_13/ /' | sudo tee /etc/apt/sources.list.d/shells:fish:release:4.list
        curl -fsSL https://download.opensuse.org/repositories/shells:fish:release:4/Debian_13/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/shells_fish_release_4.gpg > /dev/null
        apt update
        apt install -y fish vim make
        chsh -s $(which fish) {{.User}}
        chsh -s $(which fish)
        hostnamectl set-hostname debian
        reboot
      fi


probes:
  - script: |
      #!/bin/sh
      if ! timeout 30s bash -c "until test -f /usr/bin/fish; do sleep 3; done"; then
           echo >&2 "fish is not installed yet"
           exit 1
      fi

ssh:
  loadDotSSHPubKeys: true

networks:
  - vzNAT: true
    interface: "eth1"

portForwards:
  - ignore: true
    proto: any
    guestIP: 0.0.0.0
vmType: vz
arch: aarch64
cpus: 4
memory: 12GiB
disk: 50GiB
upgradePackages: true
user:
  home: /home/{{.User}}
```
### Main template
```yaml
base:
  - base/debian.yaml
```

### Issue:
DNS setting set on the base template is not propagated to the main template. Not sure if `hostResolver` settings are also propagated.

### PR DESCRIPTION
**Pull request by opjt**
## Summary

  `del($b.dns, $c.dns)` uses absolute variable paths, which are evaluated
  independently of the pipeline state in yqlib.  So even when
  `$a | select(.dns)` produces an empty pipeline (main template has no DNS),
  the del still executes and removes DNS from $b and $c.

  Fixed by using `$b | select($a.dns | length > 0) | del(.dns)` so the
  deletion only runs when the main template actually has DNS entries.

  Fixes #4760

### CODE REVIEW

File: pkg/limatmpl/embed.go [hunk 1]
```diff
@@ -225,7 +225,8 @@ const mergeDocuments = `
 | $b | select((.base | tag == "!!str") and ($a.base | tag == "!!seq")) | .base = [ "" + .base ]
 
 # Delete base DNS entries if the template list is not empty.
-| $a | select(.dns) | del($b.dns, $c.dns)
+| $b | select($a.dns | length > 0) | del(.dns)
+| $c | select($a.dns | length > 0) | del(.dns)
```
Comment (jandubois) [inline pkg/limatmpl/embed.go:229]: I'm not sure if deleting from `$c` is necessary because lists are merged only from `$b`. But it was in the original code and is defensive coding, so maybe we should keep it.

**Review by jandubois — APPROVED** [review]
> `del($b.dns, $c.dns)` uses absolute variable paths, which are evaluated independently of the pipeline state in yqlib. So even when `$a | select(.dns)` produces an empty pipeline (main template has no DNS), the `del` still executes and removes DNS from `$b` and `$c`.

Is this documented anywhere? Or just something that seems to be true empirically? I'm wondering if this is something that should be reported against `yqlib`.

---

Thanks, LGTM

**Comment by opjt** [comment]
> Is this documented anywhere? Or just something that seems to be true empirically? I'm wondering if this is something that should be reported against `yqlib`.


I found this empirically through debugging. 
I believe this is expected behavior in yqlib rather than a bug — `del($b.dns)` is an explicit operation on a variable, so it makes sense that it runs independently of the pipeline state.

**Comment by jandubois** [comment]
> I believe this is expected behavior in yqlib rather than a bug — `del($b.dns)` is an explicit operation on a variable, so it makes sense that it runs independently of the pipeline state.

I don't know; I still find it confusing. I've filed https://github.com/mikefarah/yq/issues/2652 to get clarification.

Changed my mind again and closed the issue. 😄

**Comment by jandubois** [comment]
CI is failing on Arch;  failure is unrelated to this PR. #4805

**Comment by jandubois** [comment]
> CI is failing on Arch

Please rebase your PR on latest `master`
