### PR TITLE
Check that input is a tty before using it

### LINKED ISSUE #4410: signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10fddebb6
### Description

```shell
┌─ user@c02fldw5md6m:~/Downloads 
└──❯ nerdctl.lima ps -a
? Do you want to start the instance now?  No

┌─ user@c02fldw5md6m:~/Downloads 
└──❯ yes n | nerdctl.lima ps -a
? Do you want to start the instance now?  (Y/n) ^[[55;214R^[[55;49Rpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10fddebb6]

goroutine 1 [running]:
github.com/AlecAivazis/survey/v2/terminal.(*RuneReader).ReadLineWithDefault.func2(...)
        github.com/AlecAivazis/survey/v2@v2.3.7/terminal/runereader.go:65
github.com/AlecAivazis/survey/v2/terminal.(*RuneReader).ReadLineWithDefault(0xc0005b46c0, 0x0, {0x1115a2f20, 0x0, 0x0}, {0x0?, 0xc000665340?, 0x10f359b25?})
        github.com/AlecAivazis/survey/v2@v2.3.7/terminal/runereader.go:328 +0x976
github.com/AlecAivazis/survey/v2/terminal.(*RuneReader).ReadLine(...)
        github.com/AlecAivazis/survey/v2@v2.3.7/terminal/runereader.go:37
github.com/AlecAivazis/survey/v2.(*Confirm).getBool(0xc00059e0b0, 0x0, 0xc0001ce308)
        github.com/AlecAivazis/survey/v2@v2.3.7/confirm.go:59 +0x11e
github.com/AlecAivazis/survey/v2.(*Confirm).Prompt(0xc00059e0b0, 0xc0001ce308)
        github.com/AlecAivazis/survey/v2@v2.3.7/confirm.go:137 +0xee
github.com/AlecAivazis/survey/v2.Ask({0xc0006657e0, 0x1, 0x4?}, {0x1102b94c0, 0xc0003d031c}, {0x0, 0x0, 0x10ffc2005?})
        github.com/AlecAivazis/survey/v2@v2.3.7/survey.go:366 +0x3f3
github.com/AlecAivazis/survey/v2.AskOne(...)
        github.com/AlecAivazis/survey/v2@v2.3.7/survey.go:283
github.com/lima-vm/lima/v2/pkg/uiutil.Confirm({0x110013b7d, 0x27}, 0x1)
        github.com/lima-vm/lima/v2/pkg/uiutil/uiutil.go:24 +0xe6
main.askWhetherToStart(...)
        github.com/lima-vm/lima/v2/cmd/limactl/edit.go:185
main.shellAction(0xc00054af08, {0xc000544aa0, 0x4, 0x5})
        github.com/lima-vm/lima/v2/cmd/limactl/shell.go:104 +0x439
github.com/spf13/cobra.(*Command).execute(0xc00054af08, {0xc000544a50, 0x5, 0x5})
        github.com/spf13/cobra@v1.10.1/command.go:1015 +0xb02
github.com/spf13/cobra.(*Command).ExecuteC(0xc00054a308)
        github.com/spf13/cobra@v1.10.1/command.go:1148 +0x465
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.10.1/command.go:1071
main.main()
        github.com/lima-vm/lima/v2/cmd/limactl/main.go:50 +0x6f

┌─ user@c02fldw5md6m:~/Downloads [SIGPIPE|2]
└──❯

```

### PR DESCRIPTION
**Pull request by afbjorklund**
Closes #4410

Also makes sure that `shell` checks the --tty flag

Could probably use some tests, this is code only

### CODE REVIEW

File: pkg/uiutil/uiutil.go [hunk 1]
```diff
@@ -41,6 +41,17 @@ func Select(message string, options []string) (int, error) {
 	return ans, nil
 }
 
+// InputIsTTY returns true if reader is coming from stdin, and stdin is a terminal device,
+// not a regular file, stream, or pipe etc.
+func InputIsTTY(reader io.Reader) bool {
+	// This setting is needed so we can write integration tests for the TTY input.
```
Comment (AkihiroSuda) [inline pkg/uiutil/uiutil.go]: The test seems missing?

Comment (AkihiroSuda) [reply pkg/uiutil/uiutil.go]: @afbjorklund Do you plan to add a test, or should this be merged as-is?

Comment (afbjorklund) [reply pkg/uiutil/uiutil.go]: There is an existing test for stdout, but I haven't started writing one for stdin

Comment (afbjorklund) [reply pkg/uiutil/uiutil.go]: The code didn't help with testing, so removed it (and added a real test instead)

**Comment by afbjorklund** [comment]
Added a test, here are the results with the old code:

```
 ✗ lima stopped lima instance
   (in test file hack/bats/tests/shell.bats, line 20)
     `limactl shell --tty=false "$NAME" true </dev/null' failed
? Do you want to start the instance now?  (Y/n) time="2025-12-17T07:53:09+01:00" level=fatal msg=EOF
 ✗ yes | stopped lima instance
   (in test file hack/bats/tests/shell.bats, line 25)
     `bash -c "yes | limactl shell --tty=true $NAME true"' failed with status 2
? Do you want to start the instance now?  (Y/n) panic: runtime error: invalid memory address or nil pointer dereference
   [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfa56f6]
```

Now the results are consistent, although confusing:

* https://github.com/lima-vm/lima/issues/3995

i.e. the `yes`  is discarded (like --yes).

But at least it is not crashing anymore...

**Review by AkihiroSuda — APPROVED** [review]
Thanks
