### PR TITLE
Don't use dockerhub to avoid hitting rate limits in CI

### LINKED ISSUE #260: Dockerhub rate limit causes test failures
Maybe we should push an image to the Github container registry and use that for testing?

```
time="2021-09-21T23:40:07Z" level=fatal msg="failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/alpine/manifests/sha256:e1c082e3d3c45cccac829840a25941e679c25d438cc8412c2fa221cf1a824e6a: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"
```

### PR DESCRIPTION
**Pull request by jandubois**
Fixes #260

Also removes unused `networks.LimaScheme` constant.

### CODE REVIEW

File: hack/test-example.sh [hunk 1]
```diff
@@ -170,7 +170,7 @@ if [[ -n ${CHECKS["containerd-user"]} ]]; then
 		mkdir -p "$hometmp"
 		defer "rm -rf \"$hometmp\""
 		set -x
-		limactl shell "$NAME" nerdctl pull alpine
+		limactl shell "$NAME" nerdctl pull ghcr.io/containerd/alpine:3.14.0
 		echo "random-content-${RANDOM}" >"$hometmp/random"
 		expected="$(cat "$hometmp/random")"
 		got="$(limactl shell "$NAME" nerdctl run --rm -v "$hometmp/random":/mnt/foo alpine cat /mnt/foo)"
```
Comment (AkihiroSuda) [inline hack/test-example.sh:176]: "alpine" here needs to be updated too

File: hack/test-example.sh [hunk 2]
```diff
@@ -170,10 +170,10 @@ if [[ -n ${CHECKS["containerd-user"]} ]]; then
 		mkdir -p "$hometmp"
 		defer "rm -rf \"$hometmp\""
 		set -x
-		limactl shell "$NAME" nerdctl pull alpine
+		limactl shell "$NAME" nerdctl pull ghcr.io/containerd/alpine:3.14.0
 		echo "random-content-${RANDOM}" >"$hometmp/random"
 		expected="$(cat "$hometmp/random")"
-		got="$(limactl shell "$NAME" nerdctl run --rm -v "$hometmp/random":/mnt/foo alpine cat /mnt/foo)"
+		got="$(limactl shell "$NAME" nerdctl run --rm -v "$hometmp/random":/mnt/foo alpine:3.14.0 cat /mnt/foo)"
```
Comment (AkihiroSuda) [inline hack/test-example.sh:176]: ghcr.io/containerd/alpine:3.14.0

**Review by AkihiroSuda — APPROVED** [review]
