### PR TITLE
vz: remove spice

### LINKED ISSUE #1260: [EC2 mac without GUI] `[VZSpiceAgent initialize]` crashes with `NSInvalidArgumentException`
On EC2 mac without GUI, `[VZSpiceAgent initialize]` (via `newVZVirtualMachineWithDispatchQueue`) crashes with `NSInvalidArgumentException`

( Workaround: enable GUI https://aws.amazon.com/premiumsupport/knowledge-center/ec2-mac-instance-gui-access/ )

```console
ec2-user@Mac-mini ~ % uname -a
Darwin Mac-mini.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 arm64

ec2-user@Mac-mini ~ % sw_vers 
ProductName:		macOS
ProductVersion:		13.0.1
BuildVersion:		22A400

ec2-user@Mac-mini ~ % xcrun --show-sdk-version
13.0

ec2-user@Mac-mini ~ % brew info lima
==> lima: stable 0.14.1 (bottled), HEAD
Linux virtual machines
https://github.com/lima-vm/lima
/opt/homebrew/Cellar/lima/0.14.1 (72 files, 39MB) *
  Poured from bottle on 2022-12-23 at 03:41:27
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/lima.rb
License: Apache-2.0
==> Dependencies
Build: go ✘
Required: qemu ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Analytics
install: 35,822 (30 days), 87,778 (90 days), 279,400 (365 days)
install-on-request: 18,506 (30 days), 48,562 (90 days), 165,732 (365 days)
build-error: 16 (30 days)

ec2-user@Mac-mini ~ % softwareupdate --install-rosetta
I have read and agree to the terms of the software license agreement. A list of Apple SLAs may be found here: http://www.apple.com/legal/sla/
Type A and press return to agree: A
2022-12-23 03:46:48.394 softwareupdate[10763:29384] Package Authoring Error: 012-93827: Package reference com.apple.pkg.RosettaUpdateAuto is missing installKBytes attribute
Install of Rosetta 2 finished successfully

ec2-user@Mac-mini ~ % limactl start template://experimental/vz
? Creating an instance "vz" Proceed with the current configuration
INFO[0001] Attempting to download the image from "https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-arm64.img"  digest=
INFO[0002] Using cache "/Users/ec2-user/Library/Caches/lima/download/by-url-sha256/17dad398d7fab7f11627da46d973b43a812847ace3b3216a590667981417c25d/data" 
INFO[0008] Attempting to download the nerdctl archive from "https://github.com/containerd/nerdctl/releases/download/v1.1.0/nerdctl-full-1.1.0-linux-arm64.tar.gz"  digest="sha256:3b613a1be5a24460c44bb93a3609b790ada94e06efd1a86467d45bec7da8b449"
INFO[0008] Using cache "/Users/ec2-user/Library/Caches/lima/download/by-url-sha256/c69be86b3e48430e3d687d54361cf15b90e2c067fae6a294ca6292d41f42bf0e/data" 
INFO[0010] [hostagent] Starting VZ (hint: to watch the boot progress, see "/Users/ec2-user/.lima/vz/serial.log") 
INFO[0010] [hostagent] Setting up Rosetta share         
INFO[0010] [hostagent] 2022-12-23 03:49:41.973 limactl[10996:30323] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]' 
INFO[0010] [hostagent] *** First throw call stack:      
INFO[0010] [hostagent] (                                
INFO[0010] [hostagent] 	0   CoreFoundation                      0x00000001abcf4418 __exceptionPreprocess + 176 
INFO[0010] [hostagent] 	1   libobjc.A.dylib                     0x00000001ab83eea8 objc_exception_throw + 60 
INFO[0010] [hostagent] 	2   CoreFoundation                      0x00000001abdd9cc4 -[__NSCFString characterAtIndex:].cold.1 + 0 
INFO[0010] [hostagent] 	3   CoreFoundation                      0x00000001abde6c48 -[__NSPlaceholderDictionary initWithCapacity:].cold.1 + 0 
INFO[0010] [hostagent] 	4   CoreFoundation                      0x00000001abc03818 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 320 
INFO[0010] [hostagent] 	5   CoreFoundation                      0x00000001abc036ac +[NSDictionary dictionaryWithObjects:forKeys:count:] + 52 
INFO[0010] [hostagent] 	6   Virtualization                      0x0000000212c7202c +[VZSpiceAgent initialize] + 300 
INFO[0010] [hostagent] 	7   libobjc.A.dylib                     0x00000001ab82ec98 CALLING_SOME_+initialize_METHOD + 24 
INFO[0010] [hostagent] 	8   libobjc.A.dylib                     0x00000001ab82e980 initializeNonMetaClass + 608 
INFO[0010] [hostagent] 	9   libobjc.A.dylib                     0x00000001ab8496ac _ZL24initializeAndMaybeRelockP10objc_classP11objc_objectR12locker_mixinIN9lockdebug10lock_mixinI16objc_lock_base_tEEEb + 184 
INFO[0010] [hostagent] 	10  libobjc.A.dylib                     0x00000001ab82e26c lookUpImpOrForward + 1052 
INFO[0010] [hostagent] 	11  libobjc.A.dylib                     0x00000001ab82db64 _objc_msgSend_uncached + 68 
INFO[0010] [hostagent] 	12  Virtualization                      0x0000000212bda87c -[VZSpiceAgentPortAttachment _makeGuestAgentForVirtualMachine:withConsolePort:] + 120 
INFO[0010] [hostagent] 	13  Virtualization                      0x0000000212c18e2c __48-[VZVirtualMachine initWithConfiguration:queue:]_block_invoke.51 + 880 
INFO[0010] [hostagent] 	14  CoreFoundation                      0x00000001abc6d09c __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ + 24 
INFO[0010] [hostagent] 	15  CoreFoundation                      0x00000001abc82874 -[__NSSingleObjectArrayI enumerateObjectsWithOptions:usingBlock:] + 92 
INFO[0010] [hostagent] 	16  Virtualization                      0x0000000212c15214 -[VZVirtualMachine initWithConfiguration:queue:] + 6960 
INFO[0010] [hostagent] 	17  limactl                             0x0000000100eac008 newVZVirtualMachineWithDispatchQueue + 52 
INFO[0010] [hostagent] 	18  limactl                             0x0000000100eab188 _cgo_594b7d00e505_Cfunc_newVZVirtualMachineWithDispatchQueue + 40 
INFO[0010] [hostagent] 	19  limactl                             0x00000001007ededc runtime.asmcgocall.abi0 + 124 
INFO[0010] [hostagent] )                                
INFO[0010] [hostagent] libc++abi: terminating with uncaught exception of type NSException 
INFO[0010] [hostagent] SIGABRT: abort                   
INFO[0010] [hostagent] PC=0x1abb63224 m=4 sigcode=0     
INFO[0010] [hostagent] signal arrived during cgo execution 
INFO[0010] [hostagent] goroutine 1 [syscall]:           
INFO[0010] [hostagent] runtime.cgocall(0x100eab160, 0x14000499708) 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/cgocall.go:158 +0x54 fp=0x140004996d0 sp=0x14000499690 pc=0x10078c374 
INFO[0010] [hostagent] github.com/Code-Hex/vz/v3._Cfunc_newVZVirtualMachineWithDispatchQueue(0x600003f5c000, 0x600002650400, 0x1400058e178) 
INFO[0010] [hostagent] 	_cgo_gotypes.go:1348 +0x38 fp=0x14000499700 
INFO[0010] [hostagent] github.com/Code-Hex/vz/v3.NewVirtualMachine.func1(0x10109e400?,  
INFO[0010] [hostagent] 0x14000580510?, 0x1010bc201?)    
INFO[0010] [hostagent] 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/!code-!hex/vz/v3@v3.0.2/virtualization.go:117 +0xa8 fp=0x14000499750 sp=0x14000499700 pc=0x100e4c6a8 
INFO[0010] [hostagent] github.com/Code-Hex/vz/v3.NewVirtualMachine( 
INFO[0010] [hostagent] 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/!code-!hex/vz/v3@v3.0.2/virtualization.go 
INFO[0010] [hostagent] 117 +0xd8 fp=0x140004997d0 sp=0x14000499750 
INFO[0010] [hostagent] 0x100e4c4e8                      
INFO[0010] [hostagent] github.com/lima-vm/lima/pkg/vz.createVM( 
INFO[0010] [hostagent] 0x140001fe040?, 0x1297879c8?)    
INFO[0010] [hostagent] 	/private/tmp/lima-20221214-12675-1cw7myp/lima-0.14.1/pkg/vz/vm_darwin.go:138 +0xc8 fp=0x14000499810 sp=0x140004997d0 pc=0x100e51208 
INFO[0010] [hostagent] github.com/lima-vm/lima/pkg/vz.startVM({0x10123dd90?, 0x140001ae008} 
INFO[0010] [hostagent] 0x140001a5950)                   
INFO[0010] [hostagent] 	/private/tmp/lima-20221214-12675-1cw7myp/lima-0.14.1/pkg/vz/vm_darwin.go:33 +0x3c fp=0x14000499890 sp=0x14000499810 pc=0x100e509fc 
INFO[0010] [hostagent] github.com/lima-vm/lima/pkg/vz.(*LimaVzDriver).Start(0x1400035bf50, {0x10123dd90, 0x140001ae008} 
INFO[0010] [hostagent] /private/tmp/lima-20221214-12675-1cw7myp/lima-0.14.1/pkg/vz/vz_driver_darwin.go:106 +0xc4 fp=0x14000499930 sp=0x14000499890 pc=0x100e53474 
INFO[0010] [hostagent] github.com/lima-vm/lima/pkg/hostagent.(*HostAgent).Run(0x140001b27e0, {0x10123dd90?, 0x140001ae008}) 
INFO[0010] [hostagent] 	/private/tmp/lima-20221214-12675-1cw7myp/lima-0.14.1/pkg/hostagent/hostagent.go:257 +0x2c0 fp=0x14000499b90 
INFO[0010] [hostagent] 0x14000499930 pc=0x100e947d0     
INFO[0010] [hostagent] main.hostagentAction(0x14000300600, {0x140002d99d0, 0x1, 0x7?}) 
INFO[0010] [hostagent] 	/private/tmp/lima-20221214-12675-1cw7myp/lima-0.14.1/cmd/limactl/hostagent.go:99 +0x650 
INFO[0010] [hostagent] 0x14000499d20 sp=0x14000499b90 pc=0x100ea0d70 
INFO[0010] [hostagent] github.com/spf13/cobra.(*Command).execute(0x14000300600, {0x140002d9960, 0x7, 0x7}) 
INFO[0010] [hostagent] 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c8 fp=0x14000499e60 sp=0x14000499d20 pc=0x100de3218 
INFO[0010] [hostagent] github.com/spf13/cobra.(*Command).ExecuteC(0x1400024e600) 
INFO[0010] [hostagent] 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c fp=0x14000499f20 sp=0x14000499e60 pc=0x100de396c 
INFO[0010] [hostagent] github.com/spf13/cobra.(*Command).Execute(...) 
INFO[0010] [hostagent] 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968 
INFO[0010] [hostagent] main.main()                      
INFO[0010] [hostagent] 	/private/tmp/lima-20221214-12675-1cw7myp/lima-0.14.1/cmd/limactl/main.go:23 +0x20 fp=0x14000499f70 sp=0x14000499f20 pc=0x100ea2c00 
INFO[0010] [hostagent] runtime.main()                   
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/proc.go:250 +0x24c fp= 
INFO[0010] [hostagent] 0x1007bfdcc                      
INFO[0010] [hostagent] runtime.goexit()                 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000499fd0 sp=0x14000499fd0 pc=0x1007ee0b4 
INFO[0010] [hostagent] goroutine 2 [force gc (idle)]:   
INFO[0010] [hostagent] runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?) 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/proc.go 
INFO[0010] [hostagent] 0xe4 fp=                         
INFO[0010] [hostagent]  sp=0x1400006ef80                
INFO[0010] [hostagent] 0x1007c0194                      
INFO[0010] [hostagent] runtime.goparkunlock(...)        
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/proc.go:369 
INFO[0010] [hostagent] runtime.forcegchelper()          
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/proc.go:302 +0xac fp=0x1400006efd0 sp=0x1400006efa0 pc=0x1007c002c 
INFO[0010] [hostagent] runtime.goexit()                 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400006efd0 sp=0x1400006efd0 pc=0x1007ee0b4 
INFO[0010] [hostagent] created by runtime.init.6        
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/proc.go:290 +0x24 
INFO[0010] [hostagent] goroutine 3 [GC sweep wait]:     
INFO[0010] [hostagent] runtime.gopark(0x0?, 0x0?, 0x0?,  
INFO[0010] [hostagent] ?)                               
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/proc.go:363 +0xe4 fp=0x1400006f770 sp=0x1400006f750 pc=0x1007c0194 
INFO[0010] [hostagent] runtime.goparkunlock(...)        
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/proc.go:369 
INFO[0010] [hostagent] runtime.bgsweep(0x0              
INFO[0010] [hostagent]  pc=0x1007ad094                  
INFO[0010] [hostagent] runtime.gcenable.func1()         
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/mgc.go:178 +0x28 fp=0x1400006f7d0 sp= 
INFO[0010] [hostagent]  pc=0x1007a1658                  
INFO[0010] [hostagent] runtime.goexit()                 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400006f7d0 sp=0x1400006f7d0 pc=0x1007ee0b4 
INFO[0010] [hostagent] created by runtime.gcenable      
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/mgc.go:178 +0x74 
INFO[0010] [hostagent] goroutine 4 [GC scavenge wait]:  
INFO[0010] [hostagent] runtime.gopark(0x14000098000?, 0x101030ea8?, 0x1?,  
INFO[0010] [hostagent] ?)                               
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/proc.go:363 + 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/proc.go:369 
INFO[0010] [hostagent] runtime.(*scavengerState).park(0x10182b080) 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/mgcscavenge.go:389 +0x5c fp=0x1400006ff80 sp=0x1400006ff50 pc=0x1007ab04c 
INFO[0010] [hostagent] runtime.bgscavenge(              
INFO[0010] [hostagent] /opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/mgcscavenge.go:617 +0x44 fp=0x1400006ffb0 sp=0x1400006ff80 pc=0x1007ab5f4 
INFO[0010] [hostagent] runtime.gcenable.func2()         
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/mgc.go:179 +0x28 fp=0x1400006ffd0 
INFO[0010] [hostagent] 0x1400006ffb0 pc=0x1007a15f8     
INFO[0010] [hostagent] runtime.goexit()                 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400006ffd0 sp=0x1400006ffd0 pc=0x1007ee0b4 
INFO[0010] [hostagent] created by runtime.gcenable      
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/mgc.go:179 + 
INFO[0010] [hostagent] goroutine 18 [finalizer wait]:   
INFO[0010] [hostagent] runtime.gopark(0x0?, 0x0?, 0x0   
INFO[0010] [hostagent] , 0x0?,                          
INFO[0010] [hostagent] :363 +0xe4 fp=                   
INFO[0010] [hostagent]  sp=0x1400006a560 pc=0x1007c0194 
INFO[0010] [hostagent] runtime.goparkunlock(...)        
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/proc.go:369 
INFO[0010] [hostagent] runtime.runfinq()                
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/mfinal.go:180 +0x120 fp=0x1400006a7d0 sp=0x1400006a580 pc=0x1007a0880 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/asm_arm64.s:1172 +0x4 
INFO[0010] [hostagent] 0x1400006a7d0 sp=0x1400006a7d0 pc=0x1007ee0b4 
INFO[0010] [hostagent] created by runtime.createfing    
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/mfinal.go:157 +0x84 
INFO[0010] [hostagent] goroutine 19 [select, locked to thread]: 
INFO[0010] [hostagent] runtime.gopark(0x1400006afa0?, 0x2?, 0x88?, 0xae?, 0x1400006af9c?) 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/proc.go:363 +0xe4 fp=0x14000080e30 sp=0x14000080e10 pc=0x1007c0194 
INFO[0010] [hostagent] runtime.selectgo(0x14000080fa0, 0x1400006af98, 0x0?, 0x0, 0x0 
INFO[0010] [hostagent] )                                
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/select.go:328 +0x688 fp=0x14000080f50 sp=0x14000080e30 pc= 
INFO[0010] [hostagent] runtime.ensureSigM.func1()       
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/signal_unix.go:991 +0x190 fp=0x14000080fd0 sp=0x14000080f50 pc=0x1007d40d0 
INFO[0010] [hostagent] runtime.goexit()                 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/asm_arm64.s:1172 + 
INFO[0010] [hostagent]  fp=0x14000080fd0 sp=0x14000080fd0 pc=0x1007ee0b4 
INFO[0010] [hostagent] created by runtime.ensureSigM    
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/signal_unix.go:974 +0xf4 
INFO[0010] [hostagent] goroutine 20 [syscall]:          
INFO[0010] [hostagent] runtime.sigNoteSleep(0x0)        
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/os_darwin.go:123 +0x20 fp=0x1400006b790 sp=0x1400006b750 
INFO[0010] [hostagent]  fp=0x1400006b7b0                
INFO[0010] [hostagent] 0x1400006b790 pc=0x1007ea24c     
INFO[0010] [hostagent] os/signal.loop()                 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/os/signal/signal_unix.go:23 + 
INFO[0010] [hostagent]  fp=0x1400006b7d0 sp=0x1400006b7b0 pc=0x100df8ddc 
INFO[0010] [hostagent] runtime.goexit()                 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/asm_arm64.s:1172 + 
INFO[0010] [hostagent]  sp=0x1400006b7d0 pc=            
INFO[0010] [hostagent] created by os/signal.Notify.func1.1 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/os/signal/signal.go:151 +0x2c 
INFO[0010] [hostagent] goroutine 29 [IO wait]:          
INFO[0010] [hostagent] runtime.gopark(0x0?,             
INFO[0010] [hostagent] 0x0?, 0x0?                       
INFO[0010] [hostagent] ?)                               
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/proc.go:363 +0xe4 fp=0x14000085b10 sp=0x14000085af0 pc=0x1007c0194 
INFO[0010] [hostagent] runtime.netpollblock(0x14000085ba8 
INFO[0010] [hostagent] 0x1?)                            
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/netpoll.go:526 +0x158 
INFO[0010] [hostagent] internal/poll.runtime_pollWait   
INFO[0010] [hostagent] ,                                
INFO[0010] [hostagent] )                                
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/netpoll.go:305 +0xa0 fp=0x14000085b80 sp= 
INFO[0010] [hostagent] internal/poll.(*pollDesc).wait(0x140001ffe80?, 0x100968c64?, 0x0) 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/internal/poll/fd_poll_runtime.go:84 +0x28 fp=0x14000085bb0 sp=0x14000085b80 pc=0x100851008 
INFO[0010] [hostagent] internal/poll.(*pollDesc).waitRead(...) 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/internal/poll/fd_poll_runtime.go:89 
INFO[0010] [hostagent] internal/poll.(*FD).Accept(0x140001ffe80) 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/internal/poll/fd_unix.go:614 +0x1d0 fp=0x14000085c50 sp=0x14000085bb0 pc=0x100855670 
INFO[0010] [hostagent] net.(*netFD).accept(0x140001ffe80) 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/net/fd_unix.go:172 +0x28 fp=0x14000085d10 sp=0x14000085c50 pc=0x10095e878 
INFO[0010] [hostagent] net.(*TCPListener).accept        
INFO[0010] [hostagent] /opt/homebrew/Cellar/go/1.19.4/libexec/src/net/tcpsock_posix.go:142 +0x28 fp=0x14000085d50 sp=0x14000085d10 pc=0x100977a08 
INFO[0010] [hostagent] net.(*TCPListener).Accept(       
INFO[0010] [hostagent] :288 +0x2c fp=0x14000085d90 sp=  
INFO[0010] [hostagent]  pc=0x1009768fc                  
INFO[0010] [hostagent] github.com/miekg/dns.(*Server).serveTCP(0x140003790e0, {0x10123d338?, 0x140001a59b0}) 
INFO[0010] [hostagent] 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/miekg/dns@v1.1.50/server.go:457 +0xe8 fp=0x14000085e70 sp=0x14000085d90 pc=0x100c947e8 
INFO[0010] [hostagent] github.com/miekg/dns.(*Server).ListenAndServe(0x140003790e0) 
INFO[0010] [hostagent] 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/miekg/dns@v1.1.50/server.go:314 + 
INFO[0010] [hostagent] 0x14000085e70 pc=0x100c93b40     
INFO[0010] [hostagent] github.com/lima-vm/lima/pkg/hostagent/dns.listenAndServe.func1( 
INFO[0010] [hostagent] 384 +0xa4 fp=                    
INFO[0010] [hostagent]  sp=                             
INFO[0010] [hostagent] runtime.goexit()                 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/asm_arm64.s:1172 + 
INFO[0010] [hostagent] 0x14000085fd0 sp=0x14000085fd0 pc=0x1007ee0b4 
INFO[0010] [hostagent] github.com/lima-vm/lima/pkg/hostagent/dns.listenAndServe 
INFO[0010] [hostagent] 	/private/tmp/lima-20221214-12675-1cw7myp/lima-0.14.1/pkg/hostagent/dns/dns.go:382 +0x29c 
INFO[0010] [hostagent] goroutine 28 [IO wait]:          
INFO[0010] [hostagent] runtime.gopark(0x140000fdda0?, 0x30?, 0x0?, 0xff?, 0x10?) 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/proc.go:363 +0xe4 fp=0x140001bd830 sp=0x140001bd810 pc=0x1007c0194 
INFO[0010] [hostagent] runtime.netpollblock(0x0?, 0x0?, 0x0?) 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/netpoll.go:526 +0x158 fp=0x140001bd870 sp=0x140001bd830 pc=0x1007b9678 
INFO[0010] [hostagent] internal/poll.runtime_pollWait(0x1297981d8 
INFO[0010] [hostagent] /opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/netpoll.go:305 +0xa0 fp=0x140001bd8a0 sp=0x140001bd870 pc=0x1007e8080 
INFO[0010] [hostagent] internal/poll.(*pollDesc).wait(0x140000ba380?, 0x140000c4800?, 0x0) 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/internal/poll/fd_poll_runtime.go:84 +0x28 fp=0x140001bd8d0 sp=0x140001bd8a0 pc= 
INFO[0010] [hostagent] internal/poll.(*pollDesc).waitRead(...) 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/internal/poll/fd_poll_runtime.go:89 
INFO[0010] [hostagent] internal/poll.(*FD).ReadMsgInet4(0x140000ba380, {0x140000c4800, 0x200, 0x200}, {0x1400004a440, 0x20, 0x20}, 0x140000101b8?, 0x0?) 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/internal/poll/fd_unix.go:331 +0x1f4 fp=0x140001bd9a0 sp=0x140001bd8d0 pc=0x100853564 
INFO[0010] [hostagent] net.(*netFD).readMsgInet4(0x140000ba380 
INFO[0010] [hostagent] {0x140000c4800?,                 
INFO[0010] [hostagent] }, {0x1400004a440                
INFO[0010] [hostagent] , 0x10079565c?, 0x140001bdab8?}, 0x1007ddaec?, 0x140000101b8?) 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/net/fd_posix.go:84 +0x2c fp=0x140001bda20 sp=0x140001bd9a0 pc=0x10095d18c 
INFO[0010] [hostagent] net.(*UDPConn).readMsg(0x14000072900?, {0x140000c4800? 
INFO[0010] [hostagent] 0xdb78?,                         
INFO[0010] [hostagent] , 0x400?, 0x14000072900          
INFO[0010] [hostagent] })                               
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/net/udpsock_posix.go:101 +0x124 fp=0x140001bdb20 sp=0x140001bda20 pc=0x10097a704 
INFO[0010] [hostagent] net.(*UDPConn).ReadMsgUDPAddrPort(0x140000101a0 
INFO[0010] [hostagent] {0x140000c4800?, 0x14000072900?, 0x1400004a440?},  
INFO[0010] [hostagent] 0x1400004a440?                   
INFO[0010] [hostagent] 0x140001bdc18?}                  
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/net/udpsock.go:203 
INFO[0010] [hostagent] 0x34 fp=0x140001bdbb0 sp=0x140001bdb20 pc=0x100978af4 
INFO[0010] [hostagent] net.(*UDPConn).ReadMsgUDP(       
INFO[0010] [hostagent] , {0x140000c4800?, 0x140001bdc68?, 0x10080359c?} 
INFO[0010] [hostagent] {0x1400004a440?, 0x200           
INFO[0010] [hostagent] })                               
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/net/udpsock.go: 
INFO[0010] [hostagent] 0x24 fp=0x140001bdc20 sp=        
INFO[0010] [hostagent]  pc=                             
INFO[0010] [hostagent] github.com/miekg/dns.ReadFromSessionUDP( 
INFO[0010] [hostagent] 0x140003790b0?, {0x140000c4800, 0x200, 0x200}) 
INFO[0010] [hostagent] 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/miekg/dns@v1.1.50/udp.go:42 + 
INFO[0010] [hostagent] 0x100ca41dc                      
INFO[0010] [hostagent] github.com/miekg/dns.(*Server).readUDP(0x14000378fc0 
INFO[0010] [hostagent] 0x140001bdd01?)                  
INFO[0010] [hostagent] 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/miekg/dns@v1.1.50/server.go:695 +0x16c fp=0x140001bdd20 sp= 
INFO[0010] [hostagent] github.com/miekg/dns.defaultReader.ReadUDP( 
INFO[0010] [hostagent] 0x4081c                          
INFO[0010] [hostagent] 0x10123a618?, 0x14000378fc0      
INFO[0010] [hostagent] )                                
INFO[0010] [hostagent] 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/miekg/dns@v1.1.50/server.go:174 +0x1c fp=0x140001bdd50 
INFO[0010] [hostagent] 0x140001bdd20 pc=0x100c9356c     
INFO[0010] [hostagent] github.com/miekg/dns.(*Server).serveUDP(0x14000378fc0 
INFO[0010] [hostagent] 0x1012431f0?, 0x140000101a0?})   
INFO[0010] [hostagent] 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/miekg/dns@v1.1.50/server.go:513 +0x214 fp=0x140001bde70 
INFO[0010] [hostagent] github.com/miekg/dns.(*Server).ListenAndServe(0x14000378fc0) 
INFO[0010] [hostagent] 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/miekg/dns@v1.1.50/server.go:342 
INFO[0010] [hostagent] 0x428 fp=0x140001bdf50 sp=       
INFO[0010] [hostagent] github.com/lima-vm/lima/pkg/hostagent/dns.listenAndServe.func1() 
INFO[0010] [hostagent] 	/private/tmp/lima-20221214-12675-1cw7myp/lima-0.14.1/pkg/hostagent/dns/dns.go:384 +0xa4 
INFO[0010] [hostagent] 0x140001bdfd0 sp=                
INFO[0010] [hostagent] runtime.goexit()                 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140001bdfd0 sp=0x140001bdfd0 pc=0x1007ee0b4 
INFO[0010] [hostagent] created by github.com/lima-vm/lima/pkg/hostagent/dns.listenAndServe 
INFO[0010] [hostagent] 	/private/tmp/lima-20221214-12675-1cw7myp/lima-0.14.1/pkg/hostagent/dns/dns.go:382 +0x29c 
INFO[0010] [hostagent] goroutine 27 [IO wait]:          
INFO[0010] [hostagent] runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?) 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/proc.go 
INFO[0010] [hostagent]  +0xe4                           
INFO[0010] [hostagent] 0x14000086b80 sp=                
INFO[0010] [hostagent]  pc=0x1007c0194                  
INFO[0010] [hostagent] runtime.netpollblock(0x14000086c18?, 0x855604?, 0x1?) 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/netpoll.go:526 +0x158 fp= 
INFO[0010] [hostagent] internal/poll.runtime_pollWait(0x129797ff8, 0x72 
INFO[0010] [hostagent] :305 +0xa0 fp=                   
INFO[0010] [hostagent]  sp=0x14000086bc0                
INFO[0010] [hostagent] 0x1007e8080                      
INFO[0010] [hostagent] internal/poll.(*pollDesc).wait(0x140001ffb00?, 0x10079565c?, 0x0) 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/internal/poll/fd_poll_runtime.go:84 + 
INFO[0010] [hostagent]  pc=0x100851008                  
INFO[0010] [hostagent] internal/poll.(*pollDesc).waitRead(...) 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/internal/poll/fd_poll_runtime.go:89 
INFO[0010] [hostagent] internal/poll.(*FD).Accept(0x140001ffb00) 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/internal/poll/fd_unix.go:614 +0x1d0 fp=0x14000086cc0 sp=0x14000086c20 pc= 
INFO[0010] [hostagent] net.(*netFD).accept(0x140001ffb00) 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/net/fd_unix.go:172 +0x28 
INFO[0010] [hostagent]  pc=0x10095e878                  
INFO[0010] [hostagent] net.(*UnixListener).accept(0x140000db608?) 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/net/unixsock_posix.go:166 +0x20 fp=0x14000086db0 sp=0x14000086d80 pc=0x10097de70 
INFO[0010] [hostagent] net.(*UnixListener).Accept(0x14000385830) 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/net/unixsock.go:260 +0x2c fp=0x14000086df0 sp=0x14000086db0 pc=0x10097c92c 
INFO[0010] [hostagent] net/http.(*onceCloseListener).Accept(0x10123dd90?) 
INFO[0010] [hostagent] 	<autogenerated>:1 +0x30 fp=0x14000086e10 sp=0x14000086df0 
INFO[0010] [hostagent] net/http.(*Server).Serve(0x1400027c1e0, {0x10123d368, 0x14000385830}) 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/net/http/server.go: 
INFO[0010] [hostagent] 0x100a4939c                      
INFO[0010] [hostagent] main.hostagentAction.func1()     
INFO[0010] [hostagent] 	/private/tmp/lima-20221214-12675-1cw7myp/lima-0.14.1/cmd/limactl/hostagent.go:95 +0x90 fp=0x14000086fd0 sp=0x14000086f40 pc=0x100ea0f70 
INFO[0010] [hostagent] runtime.goexit()                 
INFO[0010] [hostagent] 	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000086fd0 sp=0x14000086fd0 pc=0x1007ee0b4 
INFO[0010] [hostagent] created by main.hostagentAction  
INFO[0010] [hostagent] 	/private/tmp/lima-20221214-12675-1cw7myp/lima-0.14.1/cmd/limactl/hostagent.go:92 +0x630 
INFO[0010] [hostagent] r0      0x0                      
INFO[0010] [hostagent] r1      0x0                      
INFO[0010] [hostagent] r2      0x0                      
INFO[0010] [hostagent] r3      0x0                      
INFO[0010] [hostagent] r4      0x1abb570f5              
INFO[0010] [hostagent] r5      0x16f819a00              
INFO[0010] [hostagent] r6      0x6e                     
INFO[0010] [hostagent] r7      0x200                    
INFO[0010] [hostagent] r8      0x21eeccb303f3439        
INFO[0010] [hostagent] r9      0x21eecca5fbe8439        
INFO[0010] [hostagent] r10     0x200                    
INFO[0010] [hostagent] r11     0xb                      
INFO[0010] [hostagent] r12     0xb                      
INFO[0010] [hostagent] r13     0x1ff800                 
INFO[0010] [hostagent] r14     0x7fb                    
INFO[0010] [hostagent] r15     0x8503281b               
INFO[0010] [hostagent] r16     0x148                    
INFO[0010] [hostagent] r17     0x20c0ac9a8              
INFO[0010] [hostagent] r18     0x0                      
INFO[0010] [hostagent] r19     0x6                      
INFO[0010] [hostagent] r20     0x16f81b000              
INFO[0010] [hostagent] r21     0xe03                    
INFO[0010] [hostagent] r22     0x16f81b0e0              
INFO[0010] [hostagent] r23     0x600000a483e0           
INFO[0010] [hostagent] r24     0x600003350000           
INFO[0010] [hostagent] r25     0xb                      
INFO[0010] [hostagent] r26     0x204d47474              
INFO[0010] [hostagent] r27     0x16f81b0e0              
INFO[0010] [hostagent] r28     0x600001d54c00           
INFO[0010] [hostagent] r29     0x16f819970              
INFO[0010] [hostagent] lr      0x1abb99cec              
INFO[0010] [hostagent] sp      0x16f819950              
INFO[0010] [hostagent] pc      0x1abb63224              
INFO[0010] [hostagent] fault   0x1abb63224              
FATA[0010] host agent process has exited: exit status 2
```

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Fix #1260

### CODE REVIEW

File: pkg/vz/vm_darwin.go [hunk 1]
```diff
@@ -333,23 +333,11 @@ func attachConsole(_ *driver.BaseDriver, vmConfig *vz.VirtualMachineConfiguratio
 	if err != nil {
```
Comment (balajiv113) [inline pkg/vz/vm_darwin.go:333]: i think we can remove the entire attachConsole method itself
We can re-add this when we provide support for display.

Comment (AkihiroSuda) [reply pkg/vz/vm_darwin.go:333]: Potentially something may not work when no console is connected?

Comment (balajiv113) [reply pkg/vz/vm_darwin.go:333]: It should be fine as far as i know. Not all configs are mandatory / required to be set.

Comment (AkihiroSuda) [reply pkg/vz/vm_darwin.go]: removed the entire console

**Review by balajiv113 — APPROVED** [review]
