### PR TITLE
Minimize effects caused by restarting guestagent

### LINKED ISSUE #4216: "error":"rpc error: code = Unavailable desc = error reading from server: EOF","level":"warning","msg":"guest agent events closed unexpectedly"
### Description

Following run has uploaded artifact containing `cloud-init-output.log`, `ha.std{out,err}.log`, and `journal.log`.
https://github.com/lima-vm/lima/actions/runs/18526075404

`ha.stderr.log`:
> {"error":"rpc error: code = Unavailable desc = error reading from server: EOF","level":"warning","msg":"guest agent events closed unexpectedly","time":"2025-10-15T10:45:24Z"}

Around `2025-10-15T10:45:24Z` in `journal.log`:
> Oct 15 10:45:18 lima-default cloud-init[651]: + sudo /usr/local/bin/lima-guestagent install-systemd --debug=false --vsock-port 2222
Oct 15 10:45:19 lima-default sudo[1709]:   runner : PWD=/home/runner.linux ; USER=root ; COMMAND=/usr/bin/diff -q /run/lima-boot-done /mnt/lima-cidata/meta-data
Oct 15 10:45:19 lima-default sudo[1709]: pam_unix(sudo:session): session opened for user root(uid=0) by runner(uid=501)
Oct 15 10:45:19 lima-default sudo[1712]:     root : PWD=/ ; USER=root ; COMMAND=/usr/local/bin/lima-guestagent install-systemd --debug=false --vsock-port 2222
Oct 15 10:45:19 lima-default sudo[1709]: pam_unix(sudo:session): session closed for user root
Oct 15 10:45:19 lima-default sudo[1712]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Oct 15 10:45:19 lima-default agetty[1571]: could not get terminal name: -22
Oct 15 10:45:19 lima-default kernel: agetty[1571]: segfault at 0 ip 00007c0b78b99681 sp 00007ffc00d2c7d8 error 4 in libc.so.6[199681,7c0b78a28000+196000] likely on CPU 0 (core 0, socket 0)
Oct 15 10:45:19 lima-default kernel: Code: 84 00 00 00 00 00 0f 1f 00 f3 0f 1e fa 48 83 fa 01 7e 57 c4 41 01 ef ff 89 f8 09 f0 c1 e0 14 3d 00 00 00 f8 0f 87 a3 03 00 00 <c5> fe 6f 07 c5 fd 74 0e c5 85 74 d0 c5 ed df c9 c5 fd d7 c9 48 83
Oct 15 10:45:19 lima-default kernel: buildkit0: port 1(veth1c303502) entered blocking state
Oct 15 10:45:19 lima-default kernel: buildkit0: port 1(veth1c303502) entered forwarding state
Oct 15 10:45:20 lima-default cloud-init[651]: time="2025-10-15T10:45:19Z" level=info msg="File \"/etc/systemd/system/lima-guestagent.service\" already exists, overwriting"
Oct 15 10:45:20 lima-default cloud-init[651]: time="2025-10-15T10:45:20Z" level=info msg="Written file \"/etc/systemd/system/lima-guestagent.service\""
Oct 15 10:45:20 lima-default cloud-init[651]: time="2025-10-15T10:45:20Z" level=info msg="Executing: systemctl --system daemon-reload"
Oct 15 10:45:20 lima-default systemd[1]: Reload requested from client PID 1733 ('systemctl') (unit cloud-init-main.service)...
Oct 15 10:45:20 lima-default systemd[1]: Reloading...
Oct 15 10:45:22 lima-default sudo[1812]:   runner : PWD=/home/runner.linux ; USER=root ; COMMAND=/usr/bin/diff -q /run/lima-boot-done /mnt/lima-cidata/meta-data
Oct 15 10:45:22 lima-default sudo[1812]: pam_unix(sudo:session): session opened for user root(uid=0) by runner(uid=501)
Oct 15 10:45:22 lima-default sudo[1812]: pam_unix(sudo:session): session closed for user root
Oct 15 10:45:22 lima-default systemd[1]: Reloading finished in 2455 ms.
Oct 15 10:45:22 lima-default cloud-init[651]: time="2025-10-15T10:45:22Z" level=info msg="Executing: systemctl --system enable lima-guestagent.service"
Oct 15 10:45:22 lima-default systemd[1]: serial-getty@ttyS0.service: Deactivated successfully.
Oct 15 10:45:23 lima-default systemd[1]: serial-getty@ttyS0.service: Scheduled restart job, restart counter is at 5.
Oct 15 10:45:23 lima-default systemd[1]: Started serial-getty@ttyS0.service - Serial Getty on ttyS0.
Oct 15 10:45:23 lima-default systemd[1]: Reload requested from client PID 1827 ('systemctl') (unit cloud-init-main.service)...
Oct 15 10:45:23 lima-default systemd[1]: Reloading...
Oct 15 10:45:23 lima-default containerd-rootless-setuptool.sh[1570]: time="2025-10-15T10:45:23Z" level=info msg="found worker \"98wg5b70fpq9moc866ifjztbn\", labels=map[org.mobyproject.buildkit.worker.containerd.namespace:default org.mobyproject.buildkit.worker.containerd.uuid:f96134ea-83e5-4fd5-8348-c68709481405 org.mobyproject.buildkit.worker.executor:containerd org.mobyproject.buildkit.worker.hostname:lima-default org.mobyproject.buildkit.worker.network:cni org.mobyproject.buildkit.worker.selinux.enabled:false org.mobyproject.buildkit.worker.snapshotter:overlayfs], platforms=[linux/amd64 linux/amd64/v2 linux/amd64/v3 linux/386]"
Oct 15 10:45:23 lima-default containerd-rootless-setuptool.sh[1570]: time="2025-10-15T10:45:23Z" level=info msg="found 1 workers, default=\"98wg5b70fpq9moc866ifjztbn\""
Oct 15 10:45:23 lima-default containerd-rootless-setuptool.sh[1570]: time="2025-10-15T10:45:23Z" level=warning msg="currently, only the default worker can be used."
Oct 15 10:45:24 lima-default containerd-rootless-setuptool.sh[1570]: time="2025-10-15T10:45:24Z" level=info msg="running server on /run/user/501/buildkit-default/buildkitd.sock"
Oct 15 10:45:24 lima-default systemd[1]: Reloading finished in 1211 ms.

This seems to happen when the `lima-guestagent` installed in the previous boot was stopped, updated, and started.

If `lima-guestagent` is not updated and the startup options do not change, these steps should be skipped.
In addition, the impact on the hostagent should be minimized even if it is updated.

### PR DESCRIPTION
**Pull request by norio-nomura**
- Avoid restarting in the boot script if the executable and config have no changes.
- `lima-guestagent`: Handle SIGTERM, support save/restore `eventState` on stop/start

Fixes #4216

### CODE REVIEW

File: cmd/lima-guestagent/install_systemd_linux.go [hunk 1]
```diff
@@ -24,13 +26,18 @@ func newInstallSystemdCommand() *cobra.Command {
 		Short: "Install a systemd unit (user)",
 		RunE:  installSystemdAction,
 	}
+	installSystemdCommand.Flags().Bool("guestagent-updated", false, "Indicate that the guest agent has been updated")
```
Comment (AkihiroSuda) [inline cmd/lima-guestagent/install_systemd_linux.go:29]: Alternatively you can just compare mtime of `os.Executable` to detect whether it was updated

File: cmd/lima-guestagent/lima-guestagent.TEMPLATE.service [hunk 2]
```diff
@@ -2,7 +2,7 @@
 Description=lima-guestagent
 
 [Service]
-ExecStart={{.Binary}} daemon {{.Args}}
+ExecStart={{.Binary}} daemon {{.Args}} --runtime-dir="%t/%N"
```
Comment (AkihiroSuda) [inline cmd/lima-guestagent/lima-guestagent.TEMPLATE.service:5]: ?

File: cmd/lima-guestagent/daemon_linux.go [hunk 3]
```diff
@@ -26,6 +28,7 @@ func newDaemonCommand() *cobra.Command {
 		Short: "Run the daemon",
 		RunE:  daemonAction,
 	}
+	daemonCommand.Flags().String("runtime-dir", "/run/lima-guestagent", "Directory to store runtime state")
```
Comment (AkihiroSuda) [inline cmd/lima-guestagent/daemon_linux.go:31]: Why does this need to be customizable?

File: pkg/guestagent/guestagent_linux.go [hunk 4]
```diff
@@ -239,5 +270,42 @@ func (a *agent) Close() error {
 			return err
 		}
 	}
+	a.ticker.Stop()
 	return nil
 }
+
+const eventStateFileName = "eventState.json"
```
Comment (AkihiroSuda) [inline pkg/guestagent/guestagent_linux.go]: otherFileNamesAreNotCasedInThisWay

File: pkg/guestagent/guestagent_linux.go [hunk 5]
```diff
@@ -239,5 +270,42 @@ func (a *agent) Close() error {
...
+// SaveEventState saves the event state to a file in JSON format.
+// It overwrites the file if it already exists.
+// The saved eventState is expected to be removed on OS restart.
+func (a *agent) SaveEventState(st eventState) error {
+	logrus.Debug("Saving event state")
+	data, err := json.Marshal(st)
+	if err != nil {
+		return err
+	}
+	path := path.Join(a.runtimeDir, eventStateFileName)
```
Comment (AkihiroSuda) [inline pkg/guestagent/guestagent_linux.go]: filepath.Join should be used

File: cmd/lima-guestagent/install_systemd_linux.go (hunk 1 above)
Comment (norio-nomura) [reply cmd/lima-guestagent/install_systemd_linux.go:29]: I wanted to use the judgment result of "update guestagent" made in the boot script.
I don't want to increase the judgment logic of the update.

File: cmd/lima-guestagent/lima-guestagent.TEMPLATE.service (hunk 2 above)
Comment (norio-nomura) [reply cmd/lima-guestagent/lima-guestagent.TEMPLATE.service:5]: `"%t/%N"` will be expanded to `"/run/lima-guestagent"` by systemd.

File: cmd/lima-guestagent/daemon_linux.go (hunk 3 above)
Comment (norio-nomura) [reply cmd/lima-guestagent/daemon_linux.go:31]: for environment that does not want to use "/run/lima-guestagent"?
I don't know if there is such an environment. However, I can't think of a reason why it's better to hardcode this.

File: pkg/cidata/cidata.TEMPLATE.d/boot/25-guestagent-base.sh [hunk 6]
```diff
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
```
Comment (AkihiroSuda) [inline pkg/cidata/cidata.TEMPLATE.d/boot/25-guestagent-base.sh:1]: Does this work with Alpine?

File: pkg/guestagent/ticker/ebpf_linux.go [hunk 7]
```diff
@@ -68,6 +73,8 @@ func NewEbpfTicker(tracepoints []string) (Ticker, error) {
 	return &ticker, nil
 }
 
+var _ Ticker = (*ebpfTicker)(nil)
```
Comment (AkihiroSuda) [inline pkg/guestagent/ticker/ebpf_linux.go:76]: ?

File: pkg/guestagent/ticker/compound.go [hunk 8]
```diff
@@ -15,10 +17,13 @@ type compoundTicker struct {
 	t1, t2 Ticker
 }
 
+var _ Ticker = (*compoundTicker)(nil)
```
Comment (AkihiroSuda) [inline pkg/guestagent/ticker/compound.go:20]: ?

File: pkg/cidata/cidata.TEMPLATE.d/boot/25-guestagent-base.sh (hunk 6 above)
Comment (norio-nomura) [reply pkg/cidata/cidata.TEMPLATE.d/boot/25-guestagent-base.sh:1]: It works with both "template:alpine" and "template:alpine-iso", and has already been used in other boot scripts.

File: pkg/guestagent/ticker/ebpf_linux.go (hunk 7 above)
Comment (norio-nomura) [reply pkg/guestagent/ticker/ebpf_linux.go:76]: Let Go check whether `ebpfTicker` fits the `type Ticker interface`.
By doing this, VSCode's Go extension recognizes the relationship between these types and makes it more convenient.

**Comment by AkihiroSuda** [comment]
Needs rebase

**Comment by norio-nomura** [comment]
Thanks! 🙏🏻
