### PR TITLE
Fix for GRPC frame too large and context closed warning

### LINKED ISSUE #2216: Getting some warnings when shutting down an instance using grpc
### Description

Sometimes there is a warning issued:

```
INFO[0000] [hostagent] Received SIGINT, shutting down the host agent 
INFO[0000] [hostagent] Shutting down the host agent     
INFO[0000] [hostagent] Stopping forwarding "/run/lima-guestagent.sock" (guest) to "/home/anders/.lima/default/ga.sock" (host) 
WARN[0000] [hostagent] connection to the guest agent was closed unexpectedlyrpc error: code = Canceled desc = context canceled 
```

Maybe it now needs to stop the guest agent watch, before killing the hostagent ?

### LINKED ISSUE #2218: lima start "error reading server preface: http2: frame too large"
### Description

I'm seeing gRPC errors on lima start but I can still lima shell into the vm.

lima commit: [eb7b7e6](https://github.com/lima-vm/lima/commit/eb7b7e6)

```
$ limactl start debug
INFO[0000] Using the existing instance "debug"    
INFO[0000] Starting the instance "debug" with VM driver "vz" 
INFO[0000] [hostagent] hostagent socket created at /Users/debug/.lima/debug/ha.sock 
INFO[0000] [hostagent] Starting VZ (hint: to watch the boot progress, see "/Users/debug/.lima/debug/serial*.log") 
INFO[0000] [hostagent] new connection from  to          
INFO[0000] SSH Local Port: 54201                        
INFO[0000] [hostagent] [VZ] - vm state change: running  
INFO[0000] [hostagent] Waiting for the essential requirement 1 of 2: "ssh" 
INFO[0010] [hostagent] Waiting for the essential requirement 1 of 2: "ssh" 
INFO[0012] [hostagent] 2024/02/18 16:21:10 tcpproxy: for incoming conn 127.0.0.1:50169, error dialing "192.168.5.15:22": connect tcp 192.168.5.15:22: connection was refused 
INFO[0022] [hostagent] Waiting for the essential requirement 1 of 2: "ssh" 
INFO[0022] [hostagent] The essential requirement 1 of 2 is satisfied 
INFO[0022] [hostagent] Waiting for the essential requirement 2 of 2: "user session is ready for ssh" 
INFO[0022] [hostagent] The essential requirement 2 of 2 is satisfied 
INFO[0022] [hostagent] Waiting for the guest agent to be running 
WARN[0022] [hostagent] connection to the guest agent was closed unexpectedlyrpc error: code = Unavailable desc = connection error: desc = "error reading server preface: http2: frame too large" 
WARN[0032] [hostagent] connection to the guest agent was closed unexpectedlyrpc error: code = Unavailable desc = connection error: desc = "error reading server preface: http2: frame too large" 
WARN[0042] [hostagent] connection to the guest agent was closed unexpectedlyrpc error: code = Unavailable desc = connection error: desc = "error reading server preface: http2: frame too large" 
WARN[0052] [hostagent] connection to the guest agent was closed unexpectedlyrpc error: code = Unavailable desc = connection error: desc = "error reading server preface: http2: frame too large"
WARN[0062] [hostagent] connection to the guest agent was closed unexpectedlyrpc error: code = Unavailable desc = connection error: desc = "error reading server preface: http2: frame too large" 
WARN[0072] [hostagent] connection to the guest agent was closed unexpectedlyrpc error: code = Unavailable desc = connection error: desc = "error reading server preface: http2: frame too large" 
INFO[0082] [hostagent] Waiting for the final requirement 1 of 1: "boot scripts must have finished" 
INFO[0082] [hostagent] The final requirement 1 of 1 is satisfied 
ERRO[0082] [guest agent does not seem to be running; port forwards will not work] 
WARN[0082] DEGRADED. The VM seems running, but file sharing and port forwarding may not work. (hint: see "/Users/debug/.lima/debug/ha.stderr.log") 
FATA[0082] degraded, status={Running:true Degraded:true Exiting:false Errors:[guest agent does not seem to be running; port forwards will not work] SSHLocalPort:54201} 
```

```yaml
images:
  - location: "https://github.com/lima-vm/alpine-lima/releases/download/v0.2.35/alpine-lima-std-3.19.0-aarch64.iso"
    arch: "aarch64"
    digest: "sha512:13e50601ee65af5d7a6dfd30bb41fd89f8bf806ecdb516c61fe238c3cf3b57cf67469418a99f329bb4c343e3387e6e0fd4fe20501cfd501f031f7244adc67215"

containerd:
  system: false
  user: false
  archives:
    - location: "https://github.com/containerd/nerdctl/releases/download/v2.0.0-beta.0/nerdctl-full-2.0.0-beta.0-linux-arm64.tar.gz"
      arch: "aarch64"
      digest: "sha256:29c58dc39ebca1642f14827915f67d909ec49b1d7458938401cf835edbc5b8d0"

os: "Linux"
arch: "aarch64"
vmType: "vz"
cpus: 2
memory: "2GiB"
disk: "2GiB"

mountType: "virtiofs"
mounts:

audio:
  device: "vz"
video:
  display: "none"
networks:
  - vzNAT: true
ssh:
  localPort: 54201
  loadDotSSHPubKeys: false
  forwardAgent: false
  forwardX11: false
  forwardX11Trusted: false
```

### PR DESCRIPTION
**Pull request by balajiv113**
Fixes #2216 and tries to fix #2218

### CODE REVIEW

File: pkg/guestagent/api/client/client.go [hunk 1]
```diff
@@ -20,7 +18,7 @@ func NewGuestAgentClient(dialFn func(ctx context.Context) (net.Conn, error)) (*G
 		grpc.WithContextDialer(func(ctx context.Context, target string) (net.Conn, error) {
 			return dialFn(ctx)
 		}),
-		grpc.WithTransportCredentials(insecure.NewCredentials()),
+		grpc.WithTransportCredentials(NewCredentials()),
```
Comment (AkihiroSuda) [inline pkg/guestagent/api/client/client.go:21]: Could you explain the difference?

**Review by dj-documentation — APPROVED** [review]
Fix for #2218 confirmed

File: pkg/guestagent/api/client/client.go (hunk 1 above)
Comment (balajiv113) [reply pkg/guestagent/api/client/client.go:21]: Its more of a try out from this comment
https://github.com/open-telemetry/opentelemetry-helm-charts/issues/646#issuecomment-1832391092

I suspect, GRPC do something based on handshake response `SecurityLevel`. With insecure it will be NoSecurity. In this case it will be PrivacyAndIntegrity

**Comment by AkihiroSuda** [comment]
Lint is failing

File: pkg/vz/network_darwin.go [hunk 2]
```diff
@@ -79,7 +79,6 @@ func (v *QEMUPacketConn) Read(b []byte) (n int, err error) {
 	size := binary.BigEndian.Uint32(header)
 	reader := io.LimitReader(v.unixConn, int64(size))
 	_, err = reader.Read(b)
-
```
Comment (AkihiroSuda) [inline pkg/vz/network_darwin.go:82]: Seems added by mistake

Comment (balajiv113) [reply pkg/vz/network_darwin.go:82]: golangci-lint removed this

**Review by AkihiroSuda — APPROVED** [review]
Thanks
