### PR TITLE
Fix panic in stop when the VM goes away

### LINKED ISSUE #102: panic during `limactl stop` when the VM suddenly goes away
<details><summary>
I had a "hanging instance, and `limactl stop` would continue waiting for it to terminate. I got impatient, and ran `limactl delete -f` in a separate shell, which caused the `limactl stop` to crash:

```
2021/06/30 14:16:47 Stopping tail as file no longer exists: /Users/jan/.lima/std/ha.stdout.log
2021/06/30 14:16:47 Stopping tail as file no longer exists: /Users/jan/.lima/std/ha.stderr.log
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x144e18b]

goroutine 1 [running]:
github.com/AkihiroSuda/lima/pkg/hostagent/api.WatchEvents(0x169c9e8, 0xc00006ed20, 0xc000022990, 0x22, 0xc0000229c0, 0x22, 0xc02f55a7b59fbcc8, 0x1bceac, 0x1993120, 0xc000175b88, ...)
	/Users/jan/suse/lima/pkg/hostagent/api/eventwatcher.go:46 +0x24b
```
</summary>

```
INFO[0000] Sending SIGINT to hostagent process 25149
INFO[0000] Waiting for the host agent and the qemu processes to shut down
INFO[0000] [hostagent] Received SIGINT, shutting down the host agent
INFO[0000] [hostagent] Shutting down the host agent
INFO[0000] [hostagent] Unmounting "/Users/jan"
WARN[0000] [hostagent] connection to the guest agent was closed unexpectedly
INFO[0000] [hostagent] Shutting down QEMU with ACPI
INFO[0000] [hostagent] Sending QMP system_powerdown command
INFO[0010] [hostagent] Forwarding "/run/user/501/lima-guestagent.sock" (guest) to "/Users/jan/.lima/std/ga.sock" (host)
WARN[0010] [hostagent] failed to setting up forward from "/run/user/501/lima-guestagent.sock" (guest) to "/Users/jan/.lima/std/ga.sock" (host)
WARN[0010] [hostagent] connection to the guest agent was closed unexpectedly
INFO[0020] [hostagent] Forwarding "/run/user/501/lima-guestagent.sock" (guest) to "/Users/jan/.lima/std/ga.sock" (host)
WARN[0020] [hostagent] failed to setting up forward from "/run/user/501/lima-guestagent.sock" (guest) to "/Users/jan/.lima/std/ga.sock" (host)
WARN[0020] [hostagent] connection to the guest agent was closed unexpectedly
INFO[0030] [hostagent] Forwarding "/run/user/501/lima-guestagent.sock" (guest) to "/Users/jan/.lima/std/ga.sock" (host)
WARN[0030] [hostagent] failed to setting up forward from "/run/user/501/lima-guestagent.sock" (guest) to "/Users/jan/.lima/std/ga.sock" (host)
WARN[0030] [hostagent] connection to the guest agent was closed unexpectedly
2021/06/30 14:16:47 Stopping tail as file no longer exists: /Users/jan/.lima/std/ha.stdout.log
2021/06/30 14:16:47 Stopping tail as file no longer exists: /Users/jan/.lima/std/ha.stderr.log
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x144e18b]

goroutine 1 [running]:
github.com/AkihiroSuda/lima/pkg/hostagent/api.WatchEvents(0x169c9e8, 0xc00006ed20, 0xc000022990, 0x22, 0xc0000229c0, 0x22, 0xc02f55a7b59fbcc8, 0x1bceac, 0x1993120, 0xc000175b88, ...)
	/Users/jan/suse/lima/pkg/hostagent/api/eventwatcher.go:46 +0x24b
main.waitForHostAgentTermination(0x169c9b0, 0xc000028a68, 0xc000163ea0, 0xc02f55a7b59fbcc8, 0x1bceac, 0x1993120, 0x0, 0x0)
	/Users/jan/suse/lima/cmd/limactl/stop.go:91 +0x23c
main.stopInstanceGracefully(0xc000163ea0, 0x15e6a5b, 0x5)
	/Users/jan/suse/lima/cmd/limactl/stop.go:69 +0x2f5
main.stopAction(0xc00003d040, 0x2, 0x2)
	/Users/jan/suse/lima/cmd/limactl/stop.go:54 +0x169
github.com/urfave/cli/v2.(*Command).Run(0x1986d40, 0xc00003cf00, 0x0, 0x0)
	/Users/jan/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4dd
github.com/urfave/cli/v2.(*App).RunContext(0xc0001be000, 0x169c9b0, 0xc000028a60, 0xc00001e1b0, 0x3, 0x3, 0x0, 0x0)
	/Users/jan/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x810
github.com/urfave/cli/v2.(*App).Run(...)
	/Users/jan/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
	/Users/jan/suse/lima/cmd/limactl/main.go:15 +0x67
```
</details>

I suspect that the `Lines` channel is returning `nil` instead of a `*Line` pointer, but haven't looked further. Also not sure if this is worth spending time on, except maybe by throwing an `if line != nil` condition in there?

### PR DESCRIPTION
**Pull request by alexandear**
Fixes #102

The panic occurs because the closed channel `haStdoutTail.Lines` returns `nil` when the file `haStdoutTail` is removed.

The test has not been added because writing it without `time.Sleep` is challenging.

<details><summary>Reproducing the problem locally</summary>

#### Before the PR

```
❯ _output/bin/limactl delete -f default
...
```

```
❯ _output/bin/limactl stop default
INFO[0000] Sending SIGINT to hostagent process 37797    
INFO[0000] Waiting for the host agent and the driver processes to shut down 
INFO[0000] [hostagent] Received SIGINT, shutting down the host agent 
INFO[0000] [hostagent] Shutting down the host agent     
INFO[0000] [hostagent] Stopping forwarding "/run/lima-guestagent.sock" (guest) to "/Users/Oleksandr_Redko/.lima/default/ga.sock" (host) 
INFO[0000] [hostagent] Unmounting "/Users/Oleksandr_Redko" 
INFO[0000] [hostagent] Unmounting "/tmp/lima"           
INFO[0000] [hostagent] Shutting down QEMU with ACPI     
INFO[0000] [hostagent] Sending QMP system_powerdown command 
2024/07/09 22:52:14 Stopping tail as file no longer exists: /Users/Oleksandr_Redko/.lima/default/ha.stdout.log
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x40 pc=0x10521f66c]

goroutine 1 [running]:
github.com/lima-vm/lima/pkg/hostagent/events.Watch({0x1059712e8, 0x140004e5490}, {0x14000552200?, 0x106d57ac8?}, {0x14000552240, 0x32}, {0x30?, 0x14000089b08?, 0x10626aa20?}, 0x14000427b50)
        /Users/Oleksandr_Redko/src/github.com/lima-vm/lima/pkg/hostagent/events/watcher.go:47 +0x1ec
main.waitForHostAgentTermination({0x105971160?, 0x1067fc940?}, 0x1400047d680, {0x1?, 0x1?, 0x10626aa20?})
        /Users/Oleksandr_Redko/src/github.com/lima-vm/lima/cmd/limactl/stop.go:96 +0x13c
main.stopInstanceGracefully(0x1400047d680)
        /Users/Oleksandr_Redko/src/github.com/lima-vm/lima/cmd/limactl/stop.go:74 +0x1d0
main.stopAction(0x14000341508, {0x140004f2a00?, 0x4?, 0x1054c8577?})
        /Users/Oleksandr_Redko/src/github.com/lima-vm/lima/cmd/limactl/stop.go:53 +0xd0
github.com/spf13/cobra.(*Command).execute(0x14000341508, {0x140004f29d0, 0x1, 0x1})
        /Users/Oleksandr_Redko/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x14000340c08)
        /Users/Oleksandr_Redko/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/Oleksandr_Redko/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
main.main()
        /Users/Oleksandr_Redko/src/github.com/lima-vm/lima/cmd/limactl/main.go:27 +0x20
```

#### After the PR

```
❯ _output/bin/limactl delete -f default
...
```

```
❯ _output/bin/limactl stop default
INFO[0000] Sending SIGINT to hostagent process 34969    
INFO[0000] Waiting for the host agent and the driver processes to shut down 
INFO[0000] [hostagent] Received SIGINT, shutting down the host agent 
INFO[0000] [hostagent] Shutting down the host agent     
INFO[0000] [hostagent] Stopping forwarding "/run/lima-guestagent.sock" (guest) to "/Users/Oleksandr_Redko/.lima/default/ga.sock" (host) 
INFO[0000] [hostagent] Unmounting "/Users/Oleksandr_Redko" 
INFO[0000] [hostagent] Unmounting "/tmp/lima"           
INFO[0000] [hostagent] Shutting down QEMU with ACPI     
INFO[0000] [hostagent] Sending QMP system_powerdown command 
2024/07/09 22:49:25 Stopping tail as file no longer exists: /Users/Oleksandr_Redko/.lima/default/ha.stdout.log
FATA[0000] did not receive an event with the "exiting" status 
```

</details>

### CODE REVIEW

File: pkg/hostagent/events/watcher.go [hunk 1]
```diff
@@ -44,6 +44,9 @@ loop:
 		case <-ctx.Done():
 			break loop
 		case line := <-haStdoutTail.Lines:
+			if line == nil {
+				break loop
```
Comment (jandubois) [inline pkg/hostagent/events/watcher.go:48]: Not sure, but shouldn't we add a log message for this condition?

Comment (alexandear) [reply pkg/hostagent/events/watcher.go:48]: We already have the following log:

```
2024/07/09 22:49:25 Stopping tail as file no longer exists: /Users/Oleksandr_Redko/.lima/default/ha.stdout.log
FATA[0000] did not receive an event with the "exiting" status 
```

Not sure if we need to add another message to such a rare case.

I updated the description with logs before/after the fix.

Comment (jandubois) [reply pkg/hostagent/events/watcher.go:48]: Thanks, I missed that

**Review by jandubois — APPROVED** [review]
Thanks, LGTM
