### PR TITLE
qemuimgutil: fix "Failed to get \"write\" lock" error

### LINKED ISSUE #3720: Cannot create a VM with additional disks; qemu-img convert fails to convert to raw
### Description

After upgrading to 1.2 I can't create a VM with additional drives.

Steps to reproduce.

1. Create a disk with `limactl disk create disk1 --size 10GiB`
2. Create a template YAML `ubuntu-bug.yaml`:
```
minimumLimaVersion: 1.1.0

base:
  - template://_images/ubuntu
  - template://_default/mounts

additionalDisks:
  - name: "disk1"
    format: true
    fsType: "xfs"
```
3. Start the VM with `limactl start --name ubuntu-bug ubuntu-bug.yaml`
4. Get ERROR: `FATA[0005] exiting, status={Running:false Degraded:false Exiting:true Errors:[] SSHLocalPort:0} (hint: see "/Users/pavel/.lima/ubuntu-bug/ha.stderr.log")`
5. Check the log:
```
{"level":"info","msg":"Mounting disk \"disk1\" on \"/mnt/lima-disk1\"","time":"2025-07-11T15:10:41-04:00"}
{"level":"debug","msg":"Converting extra disk \"/Users/pavel/.lima/_disks/disk1/datadisk\" to a raw disk (if it is not a raw)","time":"2025-07-11T15:10:41-04:00"}
{"level":"fatal","msg":"failed to convert extra disk \"/Users/pavel/.lima/_disks/disk1/datadisk\" to a raw disk: failed to run [qemu-img convert -O raw /Users/pavel/.lima/_disks/disk1/datadisk /Users/pavel/.lima/_disks/disk1/datadisk]: stdout=\"\", stderr=\"qemu-img: /Users/pavel/.lima/_disks/disk1/datadisk: error while converting raw: Failed to get \\\"write\\\" lock\\nIs another process using the image [/Users/pavel/.lima/_disks/disk1/datadisk]?\\n\": exit status 1","time":"2025-07-11T15:10:41-04:00"}
```

Lima tries to use `qemu-img` to convert the disk to raw in-place and fails.

This works in 1.1.1 (just tested by installing the 1.1.1 binary).

In 1.1.1 the log looks fine:
```
{"level":"info","msg":"Mounting disk \"disk1\" on \"/mnt/lima-disk1\"","time":"2025-07-11T15:21:57-04:00"}
{"level":"debug","msg":"Converting extra disk \"/Users/pavel/.lima/_disks/disk1/datadisk\" to a raw disk (if it is not a raw)","time":"2025-07-11T15:21:57-04:00"}
{"level":"info","msg":"Converting \"/Users/pavel/.lima/_disks/disk1/datadisk\" (qcow2) to a raw disk \"/Users/pavel/.lima/_disks/disk1/datadisk\"","time":"2025-07-11T15:21:57-04:00"}
```

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Fix #3720

Thanks to @pavelanni for providing the fix generated by Claude

https://github.com/lima-vm/lima/issues/3720#issuecomment-3073777835

### CODE REVIEW

File: pkg/qemuimgutil/qemuimgutil.go [hunk 1]
```diff
@@ -103,6 +103,35 @@ type InfoFormatSpecificDataVmdkExtent struct {
...
+		}
+
+		// Replace original with converted file
+		return os.Rename(tempFile, dest)
+	}
+
+	return convertToRawHelper(source, dest)
+}
+
+func convertToRawHelper(source, dest string) error {
```
Comment (alexandear) [inline pkg/qemuimgutil/qemuimgutil.go]:
```suggestion
func execQemuImgConvert(source, dest string) error {
```

File: pkg/qemuimgutil/qemuimgutil.go [hunk 2]
```diff
@@ -103,6 +103,35 @@ type InfoFormatSpecificDataVmdkExtent struct {
...
+			return fmt.Errorf("failed to get info for source disk %q: %w", source, err)
+		}
+		// If already raw, no conversion needed
+		if info.Format == "raw" {
+			return nil
+		}
+
+		// Create temporary file for conversion
+		tempFile := dest + ".lima-qemu-convert.tmp"
+		defer os.Remove(tempFile) // Clean up temp file
```
Comment (alexandear) [inline pkg/qemuimgutil/qemuimgutil.go]: This comment is redundant and can be removed

File: pkg/qemuimgutil/qemuimgutil.go [hunk 3]
```diff
@@ -103,6 +103,35 @@ type InfoFormatSpecificDataVmdkExtent struct {
...
+		if err != nil {
+			return fmt.Errorf("failed to get info for source disk %q: %w", source, err)
+		}
+		// If already raw, no conversion needed
+		if info.Format == "raw" {
+			return nil
+		}
+
+		// Create temporary file for conversion
+		tempFile := dest + ".lima-qemu-convert.tmp"
```
Comment (alexandear) [inline pkg/qemuimgutil/qemuimgutil.go]: The comment is misleading, since the statements below don't create a file. So, we should either fix or remove the comment.

File: pkg/qemuimgutil/qemuimgutil.go [hunk 4]
```diff
@@ -103,6 +103,35 @@ type InfoFormatSpecificDataVmdkExtent struct {
...
+		defer os.Remove(tempFile) // Clean up temp file
+
+		// Convert to temp file first
```
Comment (alexandear) [inline pkg/qemuimgutil/qemuimgutil.go]: Obvious comment, can be removed.

File: pkg/qemuimgutil/qemuimgutil.go (hunk 1 above)
Comment (alexandear) [inline pkg/qemuimgutil/qemuimgutil.go]: I'm suggesting refactoring to the following:
```suggestion
	if source != dest {
		return execQemuImgConvert(source, dest)
	}

	// If source == dest, we need to use a temporary file to avoid file locking issues
	
	info, err := getInfo(source)
	if err != nil {
		return fmt.Errorf("failed to get info for source disk %q: %w", source, err)
	}
	if info.Format == "raw" {
		return nil
	}

	tempFile := dest + ".lima-qemu-convert.tmp"
	defer os.Remove(tempFile)

	if err := execQemuImgConvert(source, tempFile); err != nil {
		return err
	}

	return os.Rename(tempFile, dest)
}

func execQemuImgConvert(source, dest string) error {
```

Comment (AkihiroSuda) [reply pkg/qemuimgutil/qemuimgutil.go]: Thanks, applied

**Review by alexandear — APPROVED** [review]
Please fix lint issues.

**Comment by afbjorklund** [comment]
> Please fix lint issues.

Why does the code pass with "golangci-lint has version 2.2.1", but fail with golangci-lint 2.2.2? It's not changed.

```
Error: pkg\instance\start.go:274:65: SA4023: this comparison is always true (staticcheck)
  		if err := syscall.Exec(limactl, haCmd.Args, haCmd.Environ()); err != nil {
```

**Comment by alexandear** [comment]
> > Please fix lint issues.
> 
> Why does the code pass with "golangci-lint has version 2.2.1", but fail with golangci-lint 2.2.2? It's not changed.
> 
> ```
> Error: pkg\instance\start.go:274:65: SA4023: this comparison is always true (staticcheck)
>   		if err := syscall.Exec(limactl, haCmd.Args, haCmd.Environ()); err != nil {
> ```

It seems that golangci-lint v2.2.2 has improved detection: `syscall.Exec` always [returns an error](https://cs.opensource.google/go/go/+/refs/tags/go1.23.11:src/syscall/exec_windows.go;l=403) on Windows.

**Comment by AkihiroSuda** [comment]
This PR doesn't touch `pkg\instance\start.go`.
Why is the lint passing for master? 🤔

**Comment by AkihiroSuda** [comment]
Pushed a fix anyway

**Comment by afbjorklund** [comment]
Probably should not auto-update linters if we want a stable CI

**Comment by afbjorklund** [comment]
> Why is the lint passing for master? 🤔

Master also used golangci-lint 2.2.2

https://github.com/lima-vm/lima/actions/runs/16348933473/job/46190196998

`Run actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5`
`Run golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9`

https://github.com/lima-vm/lima/actions/runs/16344481091/job/46174596915

`Run actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5`
`Run golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9`

Seems a bit flakey. even if warning is true

**Review by alexandear — APPROVED** [review]
