### PR TITLE
print an error that wraps ExitError

### LINKED ISSUE #4167: `--network lima:shared` fails without printing an error when the sudoers file is missing
```console
$ limactl start --network lima:shared 
WARN[0000] Template locator "template://_images/ubuntu" should be written "template:_images/ubuntu" since Lima v2.0 
WARN[0000] Template locator "template://_default/mounts" should be written "template:_default/mounts" since Lima v2.0 
? Creating an instance "default" Proceed with the current configuration

$ echo $?
1
```

Lima just fails without printing an error when `--network lima:shared` is specified but `/etc/sudoers.d/lima` is missing.

The error is still printed in the debug log though:
```
DEBU[0000] Make sure "shared" network is running        
DEBU[0000] "/private/etc/sudoers.d/lima" does not exist; passwordLessSudo error: failed to run [sudo --user root --group wheel --non-interactive true]: exit status 1
```

Lima v2.0.0-alpha.2, socket_vmnet v1.2.1, macOS 26.0.1

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Fix #4167

### CODE REVIEW

File: pkg/osutil/exit.go [hunk 1]
```diff
@@ -5,18 +5,17 @@ package osutil
 
 import (
 	"errors"
-	"os"
 	"os/exec"
 )
 
-func HandleExitError(err error) {
+func HandleExitError(err error) int {
```
Comment (jandubois) [inline pkg/osutil/exit.go]: The name is now misleading because it just returns the exit error and doesn't handle it.

```suggestion
func ExitError(err error) int {
```

File: pkg/osutil/exit.go [hunk 2]
```diff
@@ -5,18 +5,17 @@ package osutil
...
 	if err == nil {
-		return
+		return 0
 	}
 
 	var exitErr *exec.ExitError
 	if errors.As(err, &exitErr) {
```
Comment (jandubois) [inline pkg/osutil/exit.go]: I think the right fix would be to change from `errors.As` back to a type assertion, so it doesn't match on wrapped ExitErrors (which is what `networks.sudo()` is returning on failure).

This is a regression that I introduced in #3938. Add a comment to make sure it isn't being changed again.

We just don't want to print a message on "naked" ExitErrors that are directly returned by `cmd.Run` etc. because then propagating the exit code is enough.

Comment (AkihiroSuda) [reply pkg/osutil/exit.go]: Fixed
