### PR TITLE
vz: Fix usernet sshLocalPort check failure for vz driver

### LINKED ISSUE #1620: [hostagent] Driver stopped due to error: "usernet unable to resolve IP for SSH forwarding"
### Description

Description:

```bash
❯ limactl start lima
INFO[0000] Using the existing instance "lima"
INFO[0000] Attempting to download the nerdctl archive    arch=x86_64 digest="sha256:3bb5f5358ee2c3bd9097e0bf37649c1775e2449094e75acf629f129ec2c7915f" location="https://github.com/containerd/nerdctl/releases/download/v1.4.0/nerdctl-full-1.4.0-linux-amd64.tar.gz"
INFO[0000] Using cache "/Users/yuan/Library/Caches/lima/download/by-url-sha256/7f7d5c10ef2e2b350e26ceca17d2e3a7ce9993c867ce53f0a1114aa0264bfb4b/data"
INFO[0000] [hostagent] Replacing "http_proxy" value "http://127.0.0.1:7890" with "http://192.168.5.2:7890"
INFO[0000] [hostagent] Replacing "https_proxy" value "http://127.0.0.1:7890" with "http://192.168.5.2:7890"
INFO[0006] [hostagent] Starting VZ (hint: to watch the boot progress, see "/Users/yuan/.lima/lima/serial.log")
INFO[0006] [hostagent] new connection from  to
INFO[0006] SSH Local Port: 60001
INFO[0006] [hostagent] [VZ] - vm state change: running
INFO[0006] [hostagent] Waiting for the essential requirement 1 of 3: "ssh"
INFO[0016] [hostagent] Waiting for the essential requirement 1 of 3: "ssh"
INFO[0026] [hostagent] Waiting for the essential requirement 1 of 3: "ssh"
INFO[0037] [hostagent] Waiting for the essential requirement 1 of 3: "ssh"
INFO[0047] [hostagent] Waiting for the essential requirement 1 of 3: "ssh"
INFO[0057] [hostagent] Waiting for the essential requirement 1 of 3: "ssh"
INFO[0066] [hostagent] Driver stopped due to error: "usernet unable to resolve IP for SSH forwarding"
INFO[0066] [hostagent] Shutting down the host agent
WARN[0066] [hostagent] failed to exit SSH master
INFO[0066] [hostagent] Shutting down VZ
INFO[0067] [hostagent] Waiting for the essential requirement 1 of 3: "ssh"
FATA[0071] exiting, status={Running:false Degraded:false Exiting:true Errors:[] SSHLocalPort:0} (hint: see "/Users/yuan/.lima/lima/ha.stderr.log")
```

Link to tracking Issue:
#1200

### PR DESCRIPTION
**Pull request by fyuan1316**
fix #1620

### CODE REVIEW

File: pkg/networks/usernet/client.go [hunk 1]
```diff
@@ -29,7 +29,7 @@ func (c *Client) UnExposeSSH(sshPort int) error {
 }
 
 func (c *Client) ResolveAndForwardSSH(vmMacAddr string, sshPort int) error {
-	timeout := time.After(1 * time.Minute)
+	timeout := time.After(3 * 500 * time.Millisecond)
```
Comment (balajiv113) [inline pkg/networks/usernet/client.go:32]: This looks wrong. You have reduced the time to 1.5s.
Also there is clash with ticker.

Eg: ticker gets called for every 500ms. Timeout being 3*500ms. Only one of the channel will get called on. And other gets discarded. In your case it is working because timeout is ignore.

I would prefer to keep timeout maybe 2 * time.Minute.

Comment (fyuan1316) [reply pkg/networks/usernet/client.go:32]: sorry, my mistake. 2 * time.Minute sounds good，thank you.

**Comment by fyuan1316** [comment]
PTAL 😄  @balajiv113

**Review by balajiv113 — APPROVED** [review]
Thanks. LGTM :)

**Comment by fyuan1316** [comment]
@balajiv113  
Thanks for taking the time to review and provide valuable feedback! Is it possible to merge if there are no other comments? 😃
