### PR TITLE
Embed binary files as base64 encoded strings

### LINKED ISSUE #3403: Embedding a larger binary file doesn't work
We can now embed data provision files:

```yaml
provision:
- mode: data
  file: binary.data
  path: /tmp/binary.data
```

But if the data file is long, this throws an error:

```
FATA[0000] Feature Retain Line Breaks BeforeAction failed with error: bufio.Scanner: token too long
```

This could probably be fixed by embedding the binary blob as a base64 encoded string using the `!!binary` tag.

### PR DESCRIPTION
**Pull request by jandubois**
They need to be broken into smaller lines; yqlib doesn't do this, and yamlfmt fails with a buffer overflow when it tries to keep existing line breaks.

Fixes #3403

### CODE REVIEW

**Comment by jandubois** [comment]
I'm going to switch this to draft because I just thought of 2 changes I want to make:

* Add an INFO level log message when a file is base64 encoded
* Check max line length for scripts / text data files, and encode them as well if they are too long

**Comment by jandubois** [comment]
> I'm going to switch this to draft because I just thought of 2 changes I want to make:
> 
> * Add an INFO level log message when a file is base64 encoded
> * Check max line length for scripts / text data files, and encode them as well if they are too long

Implemented:

```console
❯ cat tmpl.yaml
base: template://alpine
provision:
- mode: data
  file: sample.data
  path: /tmp/data
❯ perl -E 'say "A" x 66000' > sample.data
❯ limactl tmpl copy --embed-all tmpl.yaml - >/dev/null
WARN[0000] `base` is experimental
WARN[0000] `provision[*].file` and `probes[*].file` are experimental
INFO[0000] File "/Users/jan/suse/lima/sample.data" is being base64 encoded: line 1 (offset 0) is longer than 65000 characters
❯ cp /bin/cat sample.data
❯ limactl tmpl copy --embed-all tmpl.yaml - >/dev/null
WARN[0000] `base` is experimental
WARN[0000] `provision[*].file` and `probes[*].file` are experimental
INFO[0000] File "/Users/jan/suse/lima/sample.data" is being base64 encoded: unprintable character '\x00' at offset 4
```

**Comment by jandubois** [comment]
Full example:

```console
❯ cat tmpl.yaml
base: template://alpine
provision:
- mode: system
  file: my.script

❯ echo 'echo "Hello world\a\n"' > my.script
❯ hexdump -C my.script
00000000  65 63 68 6f 20 22 48 65  6c 6c 6f 20 77 6f 72 6c  |echo "Hello worl|
00000010  64 07 0a 22 0a                                    |d..".|
00000015

❯ limactl start -y tmpl.yaml
WARN[0000] `base` is experimental
WARN[0000] `provision[*].file` and `probes[*].file` are experimental
INFO[0000] File "/Users/jan/suse/lima/my.script" is being base64 encoded: unprintable character '\a' at offset 17
…

❯ grep -A2 provision ~/.lima/tmpl/lima.yaml
provision:
- mode: system
  script: !!binary ZWNobyAiSGVsbG8gd29ybGQHCiIK

❯ limactl shell tmpl sudo grep Hello /var/log/cloud-init-output.log
Hello world
```

File: pkg/limatmpl/embed.go [hunk 1]
```diff
@@ -552,11 +555,68 @@ func (tmpl *Template) combineNetworks() {
...
+		}
+		if i-start > maxLineLength {
+			encodeReason = fmt.Sprintf("line %d (offset %d) is longer than %d characters", line, start, maxLineLength)
+			break
+		}
+		if r == '\n' {
+			line++
+			start = i + 1
+		}
+	}
```
Comment (alexandear) [inline pkg/limatmpl/embed.go:609]: Could we refactor these lines to a helper function?

Something like:

```go
// ...
func encodeScriptReason(script string) string {
	start := 0
	line := 1
	for i, r := range script {
		if !(unicode.IsPrint(r) || r == '\n' || r == '\r' || r == '\t') {
			return fmt.Sprintf("unprintable character %q at offset %d", r, i)
		}
		if i-start > maxLineLength {
			return fmt.Sprintf("line %d (offset %d) is longer than %d characters", line, start, maxLineLength)
		}
		if r == '\n' {
			line++
			start = i + 1
		}
	}
	return ""
}

// updateScript replaces a "file" property with the actual script and then renames the field to newName ("script" or "content").
func (tmpl *Template) updateScript(field string, idx int, newName, script, file string) {
	tag := ""
	if reason := encodeScriptReason(script); reason != "" {
		logrus.Infof("File %q is being base64 encoded: %s", file, reason)
		script = binaryString(script)
		tag = "!!binary"
	}
	entry := fmt.Sprintf("$a.%s[%d].file", field, idx)
	// Assign script to the "file" field and then rename it to "script".
	tmpl.expr.WriteString(fmt.Sprintf("| (%s) = %q | (%s) tag = %q | (%s | key) = %q\n",
		entry, script, entry, tag, entry, newName))
}
```

File: pkg/limatmpl/embed.go [hunk 2]
```diff
@@ -552,11 +555,68 @@ func (tmpl *Template) combineNetworks() {
...
+	start := 0
+	line := 1
+	encodeReason := ""
+	for i, r := range script {
+		if !(unicode.IsPrint(r) || r == '\n' || r == '\r' || r == '\t') {
+			encodeReason = fmt.Sprintf("unprintable character %q at offset %d", r, i)
+			break
+		}
+		if i-start > maxLineLength {
+			encodeReason = fmt.Sprintf("line %d (offset %d) is longer than %d characters", line, start, maxLineLength)
```
Comment (alexandear) [inline pkg/limatmpl/embed.go:602]: It would be great to cover this line with a unit test.

Comment (jandubois) [reply pkg/limatmpl/embed.go]: I did this by changing the package name for `embed_test.go` from `limatmpl_test` to just `limatmpl`. Otherwise I would have to export `encodeScriptReason`. Neither one is desirable, but changing the test package name seems slightly better.

BTW, I know the `i-start` condition is off by 1 or 2 (depending on if you include the newline in the max line length), but since the limit is kind of arbitrary, and well below the hard limit that starts breaking, I don't think it matters. Hopefully nobody has text files with such long lines anyways.

**Comment by jandubois** [comment]
Sorry, did one more force-push to move `emcodeScriptReason` just behind the definition of `maxLineLength`, and before `binaryScript`. Feels more logical to me this way.

File: pkg/limatmpl/embed.go [hunk 3]
```diff
@@ -552,11 +555,70 @@ func (tmpl *Template) combineNetworks() {
 	}
 }
 
+// yamlfmt will fail with a buffer overflow while trying to retain line breaks if the line
+// is longer than 64K. We will encode all text files that have a line that comes close.
+const maxLineLength = 65000
```
Comment (AkihiroSuda) [inline pkg/limatmpl/embed.go:560]: Can we cover this threshold in the unit test?

Comment (jandubois) [reply pkg/limatmpl/embed.go]: I thought it was already covered by the "long line" test. I've modified it to check against a smaller threshold to make it maybe simpler.

**Comment by jandubois** [comment]
Not that it really matters, but I've decided that `maxLineLength` should include the newline at the end, so I've updated the PR once more.

File: pkg/limatmpl/embed.go [hunk 4]
```diff
@@ -552,11 +555,72 @@ func (tmpl *Template) combineNetworks() {
 	}
 }
 
+// yamlfmt will fail with a buffer overflow while trying to retain line breaks if the line
+// is longer than 64K. We will encode all text files that have a line that comes close.
+// maxLineLength is a constant; it is only a variable for the benefit of the unit tests.
+var maxLineLength = 65000
```
Comment (alexandear) [inline pkg/limatmpl/embed.go:561]: I'm not sure if it's a good idea to declare `maxLineLength` as `var` instead of `const`.
For unit tests, we can use [`strings.Repeat`](https://pkg.go.dev/strings#Repeat) to construct a very long string.

```suggestion
const maxLineLength = 65000
```

Comment (jandubois) [reply pkg/limatmpl/embed.go:561]: I was using `strings.Repeat` before, but changed it in response to a request from @AkihiroSuda to add a test for `maxLineLength'.

It is not an exported variable, and the comment right above says it is only mutable so unit tests can mock it. Unit tests should use constant data for "expected" results. Otherwise a thinko in the implementation of the function that is being tested can carry over in the test function constructing the test data and cancel out the error in the implementation. Not that it matters in a trivial case like this.


I think it is fine as is.

**Review by AkihiroSuda — APPROVED** [review]
Thanks
