### PR TITLE
Avoid warning about OS with vz driver

### LINKED ISSUE #1768: Unexpected WARN: Ignoring: vmType vz: [OS]
### Description

I always get unexpected `WARN[0000] Ignoring: vmType vz: [OS]` when trying to start virtual machines with `vmType: vz`.

```sh
$ limactl start template://experimental/vz
? Creating an instance "vz" Proceed with the current configuration
WARN[0001] `vmType: vz` is experimental
WARN[0001] Ignoring: vmType vz: [OS]
INFO[0001] Attempting to download the image              arch=aarch64 digest= location="https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-arm64.img"
Downloading the image (ubuntu-22.04-server-cloudimg-arm64.img)
...
```

Same the `--vm-type` option:

```sh
$ limactl start --name=testvz --vm-type=vz
? Creating an instance "testvz" Proceed with the current configuration
WARN[0000] `vmType: vz` is experimental
WARN[0000] Ignoring: vmType vz: [OS]
INFO[0000] Attempting to download the image              arch=aarch64 digest="sha256:af62ca6ba307388f7e0a8ad1c46103e6aea0130a09122e818df8d711637bf998" location="https://cloud-images.ubuntu.com/releases/23.04/release-20230810/ubuntu-23.04-server-cloudimg-arm64.img"
^C⏎
```

---

P.s. There is a vz instance, created months ago by colima, works fine on the machine.

```sh
$ limactl list
NAME      STATUS     SSH                VMTYPE    ARCH       CPUS    MEMORY    DISK     DIR
colima    Running    127.0.0.1:53004    vz        aarch64    2       4GiB      40GiB    ~/.lima/colima
```

---

Version:

- Hardware: M2 Mac mini (Mac14,3)
- macOS 13.5
- limactl version 0.17.2

### PR DESCRIPTION
**Pull request by cdfmlr**
Fix #1768 by:

1. add `"OS"` to the know list since #1735 introduced this field. 
2. make the log message more clear: `Ignoring: vmType vz: [...]` -> `Ignoring following configuration due to the use of vmType vz: [...]`

### CODE REVIEW

**Comment by balajiv113** [comment]
@cdfmlr Do sign your commit. DCO check is failing

Refer - https://github.com/lima-vm/lima/pull/1769/checks?check_run_id=16367811142

**Comment by cdfmlr** [comment]
> @cdfmlr Do sign your commit. DCO check is failing

Sure. Wait a moment. I'm on it.

**Comment by cdfmlr** [comment]
It might be off topic, but, I'm curious how you all sign your commits with your real names (which may not be the same as your GitHub username). I tried to do this, but the DTO validation failed with an error message like "Expected 'MY_GIT_USER_NAME SOME_RANDOM@GITHUB.NO_REPLY_EMAIL', but got 'MY_REAL_NAME ME@REAL.EMAIL'". I don't have an option but to sign off with a username😂.

**Comment by jandubois** [comment]
> I'm curious how you all sign your commits with your real names

The name and email in the DCO must match the commit author name and email of the commit.

I use a `prepare-commit-message` hook on my local machine to add the DCO with the correct name/email for the repo with something like this:

```shell
NAME=$(git config user.name)
EMAIL=$(git config user.email)

if [ -z "$NAME" ]; then
    echo "empty git config user.name"
    exit 1
fi

if [ -z "$EMAIL" ]; then
    echo "empty git config user.email"
    exit 1
fi

git interpret-trailers --if-exists doNothing --trailer \
    "Signed-off-by: $NAME <$EMAIL>" \
    --in-place "$1"
```

**Comment by cdfmlr** [comment]
Thanks @jandubois I'd like to try it in the future.

---

Forget about the signoff that does not matter. There is a test failed: 

- https://github.com/lima-vm/lima/actions/runs/6036914035/job/16393256614?pr=1769

It's a QEMU thing, which I don't think might be blame to my commit. A log modifying about vz should not hurt a QEMU vm test in anyway.

And before I do rebase --signoff, the test passed:

- https://github.com/lima-vm/lima/actions/runs/6032514141

Is it a temporary problem?

File: pkg/vz/vz_driver_darwin.go [hunk 1]
```diff
@@ -73,8 +73,9 @@ func (l *LimaVzDriver) Validate() error {
 		"AdditionalDisks",
 		"Audio",
 		"Video",
+		"OS",
 	); len(unknown) > 0 {
-		logrus.Warnf("Ignoring: vmType %s: %+v", *l.Yaml.VMType, unknown)
+		logrus.Warnf("Ignoring following configuration due to the use of vmType %s: %+v", *l.Yaml.VMType, unknown)
```
Comment (AkihiroSuda) [inline pkg/vz/vz_driver_darwin.go:78]: Probably you may want to update all the occurrences of `Ignoring: vmType %s` in this file?

Comment (AkihiroSuda) [inline pkg/vz/vz_driver_darwin.go:78]:
```suggestion
		logrus.Warnf("vmType %s: Ignoring %+v", *l.Yaml.VMType, unknown)
```

Comment (cdfmlr) [reply pkg/vz/vz_driver_darwin.go]: Resolved in [1f2c1e2](https://github.com/lima-vm/lima/pull/1769/commits/1f2c1e2ff9363f466d8f743458270f71605301f6).

Comment (cdfmlr) [reply pkg/vz/vz_driver_darwin.go]: Resolved in [1f2c1e2](https://github.com/lima-vm/lima/pull/1769/commits/1f2c1e2ff9363f466d8f743458270f71605301f6)

Comment (cdfmlr) [reply pkg/vz/vz_driver_darwin.go]: This is obviously better than the original. I totally accept it. However, forgive my wasting of time for such an irrelevant issue, I am still concern this is not clear enough for folks not familiar with it (such as the person i was days ago). Personally I'd like to make it more verbose. How do you like it?

**Review by AkihiroSuda — COMMENTED** [review]
Thanks, bur please squash commits

File: pkg/vz/vz_driver_darwin.go (hunk 1 above)
Comment (AkihiroSuda) [reply pkg/vz/vz_driver_darwin.go]: > Personally I'd like to make it more verbose.

How will it look like?

Comment (cdfmlr) [reply pkg/vz/vz_driver_darwin.go]: Perhaps like `Prefer vmType %s: Ignoring ...` or `Ignoring due to vmType %s: ...`? I am not sure

**Comment by cdfmlr** [comment]
> Thanks, but please squash commits

It's Squashed.

**Review by AkihiroSuda — APPROVED** [review]
Thanks
