### PR TITLE
vmType: default to QEMU for non-native architectures

### LINKED ISSUE #4710: vmType: default to QEMU for non-native architectures
```console
$ limactl start --name foo --arch x86_64 template:alpine
? Creating an instance "foo" Proceed with the current configuration
FATA[0000] failed to resolve vm for "/Users/suda/.lima/foo/lima.yaml": unsupported arch: "x86_64
```

This error is confusing, it should automatically fallback to QEMU, or, at least it should print a hint to suggest specifying `--vm-type=qemu`

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Fix #4710

### CODE REVIEW

File: pkg/limatype/lima_yaml.go [hunk 1]
```diff
@@ -405,3 +415,7 @@ func DefaultDriver() VMType {
 		return QEMU
```
Comment (adam-at-mobomo) [inline pkg/limatype/lima_yaml.go:415]: Shouldn't this also be changed to use `DefaultNonNativeArchDriver()`?

Comment (AkihiroSuda) [reply pkg/limatype/lima_yaml.go:415]: No
