### PR TITLE
Make errors less scary

### LINKED ISSUE #4321: Error message shown when starting lima instance
### Description

On Linux, a red error message is shown for NTP (UDP 323)

```
INFO[0018] [hostagent] Forwarding UDP from 0.0.0.0:5353 to 127.0.0.1:5353 
INFO[0018] [hostagent] Not forwarding UDP 127.0.0.54:53 
INFO[0018] [hostagent] Not forwarding UDP 127.0.0.53:53 
INFO[0018] [hostagent] Not forwarding UDP 192.168.5.15:68 
INFO[0018] [hostagent] Forwarding UDP from 127.0.0.1:323 to 127.0.0.1:323 
INFO[0018] [hostagent] Forwarding UDP from [::]:5353 to 127.0.0.1:5353 
ERRO[0018] [hostagent] failed to listen udp: listen udp 127.0.0.1:323: bind: permission denied 
INFO[0018] [hostagent] Forwarding UDP from [::1]:323 to 127.0.0.1:323 
ERRO[0018] [hostagent] failed to listen udp: listen udp 127.0.0.1:323: bind: permission denied 
```

Possibly related to portforwarding:

* https://github.com/lima-vm/lima/issues/4193

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Fix #4321 

Before
```console
$ limactl start template:ubuntu-24.04 
? Creating an instance "ubuntu-24.04" Proceed with the current configuration
INFO[0002] Starting the instance "ubuntu-24.04" with internal VM driver "vz" 
INFO[0002] Attempting to download the image              arch=aarch64 digest="sha256:2674494736319bbd367ef05c37c5dbb764fa7c90661d104ac93243ee84129ca9" location="https://cloud-images.ubuntu.com/releases/noble/release-20251026/ubuntu-24.04-server-cloudimg-arm64.img"
INFO[0002] Using cache "/Users/suda/Library/Caches/lima/download/by-url-sha256/41ca8a76b8d61aad7f42c77da508f009c098f657a1024cfd235f146e136d9d1a/data" 
INFO[0002] Converting "/Users/suda/.lima/ubuntu-24.04/basedisk" (qcow2) to a raw disk "/Users/suda/.lima/ubuntu-24.04/diffdisk" 
3.50 GiB / 3.50 GiB [---------------------------------------] 100.00% 2.17 GiB/s
INFO[0003] Expanding to 100GiB                          
INFO[0004] Attempting to download the nerdctl archive    arch=aarch64 digest="sha256:5398f037ae095d43cf3cb8c30765a24e511e38cafe02977b928a41b26e842ed1" location="https://github.com/containerd/nerdctl/releases/download/v2.2.0/nerdctl-full-2.2.0-linux-arm64.tar.gz"
INFO[0004] Using cache "/Users/suda/Library/Caches/lima/download/by-url-sha256/e27422aaa9393572e7dc134eeb158f08328f22ca5e7556c80bdd221497a0a84a/data" 
INFO[0004] [hostagent] hostagent socket created at /Users/suda/.lima/ubuntu-24.04/ha.sock 
INFO[0004] [hostagent] Starting VZ (hint: to watch the boot progress, see "/Users/suda/.lima/ubuntu-24.04/serial*.log") 
INFO[0004] [hostagent] [VZ] - vm state change: running  
WARN[0011] [hostagent] Failed to detect SSH server on vsock port, falling back to usernet forwarder  error="Error Domain=NSPOSIXErrorDomain Code=54 Description=\"The operation couldn’t be completed. Connection reset by peer\" UserInfo={\n}"
INFO[0012] SSH Local Port: 56057                        
INFO[0011] [hostagent] Waiting for the essential requirement 1 of 3: "ssh" 
INFO[0012] [hostagent] The essential requirement 1 of 3 is satisfied 
INFO[0012] [hostagent] Waiting for the essential requirement 2 of 3: "user session is ready for ssh" 
INFO[0012] [hostagent] The essential requirement 2 of 3 is satisfied 
INFO[0012] [hostagent] Waiting for the essential requirement 3 of 3: "Explicitly start ssh ControlMaster" 
INFO[0012] [hostagent] The essential requirement 3 of 3 is satisfied 
INFO[0012] [hostagent] Waiting for the optional requirement 1 of 2: "systemd must be available" 
INFO[0012] [hostagent] Guest agent is running           
INFO[0012] [hostagent] The optional requirement 1 of 2 is satisfied 
INFO[0012] [hostagent] Waiting for the optional requirement 2 of 2: "containerd binaries to be installed" 
INFO[0012] [hostagent] Not forwarding TCP 0.0.0.0:22    
INFO[0012] [hostagent] Not forwarding TCP 127.0.0.53:53 
INFO[0012] [hostagent] Not forwarding TCP 127.0.0.54:53 
INFO[0012] [hostagent] Not forwarding TCP [::]:22       
INFO[0012] [hostagent] Not forwarding UDP 127.0.0.54:53 
INFO[0012] [hostagent] Not forwarding UDP 127.0.0.53:53 
INFO[0012] [hostagent] Not forwarding UDP 192.168.5.15:68 
INFO[0012] [hostagent] Forwarding UDP from 0.0.0.0:5353 to 127.0.0.1:5353 
INFO[0012] [hostagent] Forwarding UDP from [::]:5353 to 127.0.0.1:5353 
ERRO[0012] [hostagent] failed to listen udp: listen udp 127.0.0.1:5353: bind: address already in use 
ERRO[0012] [hostagent] failed to listen udp: listen udp 127.0.0.1:5353: bind: address already in use 
ERRO[0012] [hostagent] failed to listen udp: listen udp 127.0.0.1:5353: bind: address already in use 
ERRO[0012] [hostagent] failed to listen udp: listen udp 127.0.0.1:5353: bind: address already in use 
INFO[0042] [hostagent] Forwarding UDP from 0.0.0.0:55479 to 127.0.0.1:55479 
INFO[0052] [hostagent] Waiting for the optional requirement 2 of 2: "containerd binaries to be installed" 
INFO[0074] [hostagent] Forwarding UDP from 0.0.0.0:39163 to 127.0.0.1:39163 
INFO[0087] [hostagent] Forwarding TCP from 127.0.0.1:39791 to 127.0.0.1:39791 
INFO[0092] [hostagent] Waiting for the optional requirement 2 of 2: "containerd binaries to be installed" 
INFO[0092] [hostagent] The optional requirement 2 of 2 is satisfied 
INFO[0092] [hostagent] Waiting for the guest agent to be running 
INFO[0092] [hostagent] Waiting for the final requirement 1 of 1: "boot scripts must have finished" 
INFO[0098] [hostagent] The final requirement 1 of 1 is satisfied 
INFO[0099] READY. Run `limactl shell ubuntu-24.04` to open the shell. 
```

After
```console
$ limactl start template:ubuntu-24.04 
? Creating an instance "ubuntu-24.04" Proceed with the current configuration
INFO[0000] Starting the instance "ubuntu-24.04" with internal VM driver "vz" 
INFO[0000] Attempting to download the image              arch=aarch64 digest="sha256:2674494736319bbd367ef05c37c5dbb764fa7c90661d104ac93243ee84129ca9" location="https://cloud-images.ubuntu.com/releases/noble/release-20251026/ubuntu-24.04-server-cloudimg-arm64.img"
INFO[0000] Using cache "/Users/suda/Library/Caches/lima/download/by-url-sha256/41ca8a76b8d61aad7f42c77da508f009c098f657a1024cfd235f146e136d9d1a/data" 
INFO[0000] Converting "/Users/suda/.lima/ubuntu-24.04/basedisk" (qcow2) to a raw disk "/Users/suda/.lima/ubuntu-24.04/diffdisk" 
3.50 GiB / 3.50 GiB [---------------------------------------] 100.00% 2.17 GiB/s
INFO[0002] Expanding to 100GiB                          
INFO[0002] Attempting to download the nerdctl archive    arch=aarch64 digest="sha256:5398f037ae095d43cf3cb8c30765a24e511e38cafe02977b928a41b26e842ed1" location="https://github.com/containerd/nerdctl/releases/download/v2.2.0/nerdctl-full-2.2.0-linux-arm64.tar.gz"
INFO[0002] Using cache "/Users/suda/Library/Caches/lima/download/by-url-sha256/e27422aaa9393572e7dc134eeb158f08328f22ca5e7556c80bdd221497a0a84a/data" 
INFO[0002] [hostagent] hostagent socket created at /Users/suda/.lima/ubuntu-24.04/ha.sock 
INFO[0002] [hostagent] Starting VZ (hint: to watch the boot progress, see "/Users/suda/.lima/ubuntu-24.04/serial*.log") 
INFO[0002] [hostagent] [VZ] - vm state change: running  
INFO[0009] [hostagent] SSH server does not seem running on vsock port, using usernet forwarder 
INFO[0010] SSH Local Port: 56695                        
INFO[0009] [hostagent] Waiting for the essential requirement 1 of 3: "ssh" 
INFO[0010] [hostagent] The essential requirement 1 of 3 is satisfied 
INFO[0010] [hostagent] Waiting for the essential requirement 2 of 3: "user session is ready for ssh" 
INFO[0021] [hostagent] Waiting for the essential requirement 2 of 3: "user session is ready for ssh" 
INFO[0021] [hostagent] The essential requirement 2 of 3 is satisfied 
INFO[0021] [hostagent] Waiting for the essential requirement 3 of 3: "Explicitly start ssh ControlMaster" 
INFO[0021] [hostagent] The essential requirement 3 of 3 is satisfied 
INFO[0021] [hostagent] Waiting for the optional requirement 1 of 2: "systemd must be available" 
INFO[0021] [hostagent] Guest agent is running           
INFO[0021] [hostagent] The optional requirement 1 of 2 is satisfied 
INFO[0021] [hostagent] Not forwarding TCP 127.0.0.53:53 
INFO[0021] [hostagent] Waiting for the optional requirement 2 of 2: "containerd binaries to be installed" 
INFO[0021] [hostagent] Not forwarding TCP 127.0.0.54:53 
INFO[0021] [hostagent] Not forwarding TCP 0.0.0.0:22    
INFO[0021] [hostagent] Not forwarding TCP [::]:22       
INFO[0021] [hostagent] Not forwarding UDP 127.0.0.54:53 
INFO[0021] [hostagent] Not forwarding UDP 127.0.0.53:53 
INFO[0021] [hostagent] Not forwarding UDP 192.168.5.15:68 
INFO[0021] [hostagent] Forwarding UDP from 0.0.0.0:5353 to 127.0.0.1:5353 
INFO[0021] [hostagent] Forwarding UDP from [::]:5353 to 127.0.0.1:5353 
INFO[0021] [hostagent] Not forwarding UDP 127.0.0.1:5353 
INFO[0021] [hostagent] Not forwarding UDP 127.0.0.1:5353 
INFO[0021] [hostagent] Not forwarding UDP 127.0.0.1:5353 
INFO[0021] [hostagent] Not forwarding UDP 127.0.0.1:5353 
INFO[0041] [hostagent] Forwarding UDP from 0.0.0.0:35422 to 127.0.0.1:35422 
INFO[0061] [hostagent] Waiting for the optional requirement 2 of 2: "containerd binaries to be installed" 
INFO[0073] [hostagent] Forwarding UDP from 0.0.0.0:46531 to 127.0.0.1:46531 
INFO[0101] [hostagent] Waiting for the optional requirement 2 of 2: "containerd binaries to be installed" 
INFO[0115] [hostagent] Forwarding TCP from 127.0.0.1:35485 to 127.0.0.1:35485 
INFO[0116] [hostagent] The optional requirement 2 of 2 is satisfied 
INFO[0116] [hostagent] Waiting for the guest agent to be running 
INFO[0116] [hostagent] Waiting for the final requirement 1 of 1: "boot scripts must have finished" 
INFO[0125] [hostagent] The final requirement 1 of 1 is satisfied 
INFO[0126] READY. Run `limactl shell ubuntu-24.04` to open the shell. 
```

### CODE REVIEW

File: pkg/driver/vz/vm_darwin.go [hunk 1]
```diff
@@ -116,7 +116,9 @@ func startVM(ctx context.Context, inst *limatype.Instance, sshLocalPort int) (vm
 								logrus.Infof("Detected SSH server is listening on the vsock port; changed %s to proxy for the vsock port", hostAddress)
 								usernetSSHLocalPort = 0 // disable gvisor ssh port forwarding
 							} else {
-								logrus.WithError(err).Warn("Failed to detect SSH server on vsock port, falling back to usernet forwarder")
+								logrus.WithError(err).WithField("hostAddress", hostAddress).
+									Debugf("Failed to start vsock forwarder (systemd is older than v256?)")
+								logrus.Info("SSH server does not seem running on vsock port, using usernet forwarder")
```
Comment (jandubois) [inline pkg/driver/vz/vm_darwin.go]: I think this needs "to be" to be proper English:

```suggestion
								logrus.Info("SSH server does not seem to be running on vsock port, using usernet forwarder")
```

**Review by jandubois — APPROVED** [review]
Thanks, LGTM

File: pkg/driver/vz/vm_darwin.go (hunk 1 above)
Comment (AkihiroSuda) [reply pkg/driver/vz/vm_darwin.go]: done
