### PR TITLE
CI: test UDP port forwarding

### LINKED ISSUE #3657: UDP port forwarding does not work with iperf3 and lacks tests

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Partially fix #3657

### CODE REVIEW

File: hack/test-templates.sh [hunk 1]
```diff
@@ -375,9 +375,10 @@ if [[ -n ${CHECKS["ssh-over-vsock"]} ]]; then
 	fi
 fi
 
-# Use GHCR to avoid hitting Docker Hub rate limit
+# Use GHCR and ECR to avoid hitting Docker Hub rate limit
```
Comment (jandubois) [inline hack/test-templates.sh:378]: I thought Docker and GitHub had an agreement that GitHub actions running on the GitHub runners on public repos are not subject to the pull request limits. Is this no longer the case?

I suspect the reason is that we are using a non-free runner, so the exemption does not apply. Which I guess is fair enough: if GitHub is being paid for the runner, then it can require a paid DockerHub account as well.

Comment (AkihiroSuda) [reply hack/test-templates.sh:378]: Let's try migrating to Docker Hub in a separate PR

Comment (jandubois) [reply hack/test-templates.sh:378]: It doesn't really matter which registry we use, so I don't think we need to change, except maybe to expand the comment.

I was just surprised to see that we had changed the location because of rate limits, but then I remembered that we were using non-free runners before, which might explain why this was necessary.

Comment (AkihiroSuda) [reply hack/test-templates.sh:378]: Anyway the test has to be runnable on laptops too, not just on CI

Comment (jandubois) [reply hack/test-templates.sh:378]: Sure, but I assume anyone running into pull request limits will just log in with their free DockerHub account.

Anyways, as I wrote above, we don't need to switch the images back; I was just curious.
